### PR TITLE
refactor(core/naming): Convert angular naming.service to plain NameUtils

### PR DESCRIPTION
**Pull request by jrsquared**
No need for naming.service to be in angular anymore.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
(I didn't actually look at it after the first few files, I just agree with this in principle)

**Comment by jrsquared** [comment]
Looks like you're using the `@spinnaker/google` module.  A new version has to be cut with the `NameUtils` changes. (@danielpeach any concerns cutting a new one?)

**Comment by amanya** [comment]
@jrsquared that was it, thanks for looking at it. We also use the kubernetes module, so we'll need a new release of it too.

**Pull request merged**
