### PR TITLE
feat(core/presentation): misc icons

### PR DESCRIPTION
**Pull request by gcomstock**
Screen Shot 2020-05-29 at 4 33 58 PM

for @erikmunson an @caseyhebebrand (env icon for the new nav)

thanks!
Greg

### CODE REVIEW

**Comment by caseyhebebrand** [comment]
Cool, we can make a follow up PR to add the icon names to data sources.

**Comment by gcomstock** [comment]
Whoops! I did this while on a call and spaced that out. Will fix!

**Comment by erikmunson** [comment]
@gcomstock LMK when you're ready to get this merged and I'll hit the button

**Comment by gcomstock** [comment]
hit it! Thank you.

**Pull request merged**
