### PR TITLE
(core) refactored lb and cluster dependent filters

### PR DESCRIPTION
**Pull request by danielpeach**
@anotherchrisberry please review

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Looks good - let me pull it down and run it locally to verify...

**Comment by anotherchrisberry** [comment]
If I filter by an account, clicking the region or availability zones filters doesn't do anything.

If I filter by region or zone, then filter by account, the region/zone filters get cleared, even if they're still available as options.

**Comment by danielpeach** [comment]
Very odd -- I'm not seeing any of that behavior. Is there anything I could be missing from your setup? I'm filtering aws, gcp, and kubernetes server groups all at once.

**Comment by anotherchrisberry** [comment]
Sent you a video of the unexpected behavior...

**Comment by danielpeach** [comment]
@anotherchrisberry could you take a second look?

**Comment by anotherchrisberry** [comment]
Looks good and works as expected on the clusters tab, but I do not see regions or zones filtering down on the load balancers or security groups tabs, i.e. if I select an account that's only deployed in one region, I still see all region options, and if I filter on a region, I still see all zone options.

**Comment by danielpeach** [comment]
Oh. Right. Thanks again Chris. I'm going to close and rework.

**Pull request closed without merging**
