### PR TITLE
fix(core/amazon): don't show copy capacity options for create asg

### PR DESCRIPTION
**Pull request by tomaslin**

### CODE REVIEW

**Comment by christopherthielen** [comment]
lgtm

**Comment by ajordens** [comment]
Do we care if you’re using the create flow but provided stack and freeformDetails matching an existing cluster?

In that scenario, the copy from existing is reasonable.

**Comment by tomaslin** [comment]
It's probably less surprise if they're going through a clone.

**Comment by anotherchrisberry** [comment]
LGTM. The create flow scenario where they provide an existing cluster is kind of a weird case and not one I think we need to worry about.

**Pull request merged**
