### PR TITLE
feat(Azure): Listing managed images from Azure account in BaseOs drop.

### PR DESCRIPTION
**Pull request by DanielaS12**
Enabled Managed Image search in the Azure Bake stage.

Tested on local machine, attached bellow images with the workflow:

* Added link for 'Search Managed Images'
Configuration
* When clicking on it Base Os drop down content changes with the managed images
Configuration
Configuration

### CODE REVIEW

**Review by kkotula — APPROVED** [review]

**Comment by DanielaS12** [comment]
This PR should be merged after https://github.com/spinnaker/clouddriver/pull/5795 is merged

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by mattgogerly** [comment]
@DanielaS12 is this ready to go?

**Comment by DanielaS12** [comment]
> @DanielaS12 is this ready to go? looks like there's some conflicts?

No, I am closing this pr. The changes were made in a different one.

**Pull request closed without merging**
