### PR TITLE
chore(kubernetes): Bump version to 0.0.22

### PR DESCRIPTION
**Pull request by jervi**

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@jervi do you need us to publish a new release of @spinnaker/kubernetes?

**Comment by jervi** [comment]
It was just that our custom internal deck build didn’t build after removing the moment.js dependency, because kubernetes v0.0.21 was still using it. https://github.com/spinnaker/deck/commit/3e758150672fb49e7f66e520f0b6bae87591bbc5

**Comment by jervi** [comment]
In other words, yes, but there’s no rush.

**Comment by maggieneterval** [comment]
hey @jervi! just published this package and opened this PR: https://github.com/spinnaker/deck/pull/6969,
so going to close this one.

**Pull request closed without merging**
