### PR TITLE
(core) refactor modal wizard to TS, use on Config tab

### PR DESCRIPTION
**Pull request by anotherchrisberry**
What started as a quick exercise to make the Config tab usable by humans has spiraled into almost 120 files being changed by way of refactoring the modal wizard service and directives to components written in Typescript.

I think it's worth it, but, since this has touched pretty much every single modal in the application, I would appreciate some eyes on the Kubernetes and Google modals (@lwander and/or @danielpeach). Everything else seemed to be copied without much change from those, so I feel pretty good.

The main reason this got so big was because the current wizard uses $scope inheritance to derive its task monitor, which was convenient but not a great pattern.

screen shot 2016-10-06 at 8 59 11 pm

### CODE REVIEW

**Comment by ajordens** [comment]
Since you're showing me this awesome screenshot ... what would the LOE be to make Delete Application just an icon / button (say below the box) on the left section rather than a scroll at the bottom of the right?

It's just a button or blob of text after all?

**Comment by danielpeach** [comment]
Looks really good. 

The X on the top right does not work for most of the modals for GCE and Kubernetes.

**Comment by danielpeach** [comment]
Pressed the wrong button

**Comment by lwander** [comment]
Looks like Dan's not a fan

**Comment by lwander** [comment]
Also pushed the wrong button

**Comment by duftler** [comment]
haha

**Comment by anotherchrisberry** [comment]
Fixed the modal close behavior (thanks for catching) by converting `<modal-close>` to a component with isolated scope.

**Comment by anotherchrisberry** [comment]
@ajordens it's doable (would be similar to the changes we made to collapsible section) and something to consider later.

**Comment by icfantv** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
Merging, it's just 186 files, what could go wrong.

**Pull request merged**
