### PR TITLE
Openstack: Update UI to support multiple load balancers for a server group.

### PR DESCRIPTION
**Pull request by jcwest**

### CODE REVIEW

**Comment by jcwest** [comment]
FYI: code was reviewed internally at Veritas before raising the PR.

**Comment by jcwest** [comment]
@anotherchrisberry Please take a look. Thanks!

**Comment by zanthrash** [comment]
@jcwest LGTM.  Needs a rebase

**Comment by jcwest** [comment]
@zanthrash, @anotherchrisberry: FYI: rebase done

**Pull request merged**
