### PR TITLE
fix(docker) add ProxyPreserveHost On

### PR DESCRIPTION
**Pull request by carllhw**
apache spinnaker.conf add `ProxyPreserveHost On` to preserve host to gate

### CODE REVIEW

**Comment by carllhw** [comment]
PTAL @lwander

**Comment by lwander** [comment]
What do you mean by preserve host to gate? Can you link to the apache docs that support this change?

**Comment by carllhw** [comment]
[Apache Doc - ProxyPreserveHost](https://httpd.apache.org/docs/current/mod/mod_proxy.html#proxypreservehost)

For example, the deck url is `www.example.com`, the gate proxy path is `www.example.com/gate`. 
gate has OAuth 2.0 security. When after login, the redirect url become `www.example.com:9000`.
I thinks it is because of apache do not pass the `Host` header to gate.

**Comment by lwander** [comment]
Ah yes that's very useful. Please rebase your branch & I'll merge.

**Comment by carllhw** [comment]
PTAL @lwander

**Comment by lwander** [comment]
Sorry for the wait... seems like travis-ci has stalled

**Comment by lwander** [comment]
This will appear in the next Spinnaker point release (1.5). Do you need it sooner?

**Comment by carllhw** [comment]
Nope, I build my own image base on this commit. When the deck image has this feature, I will change the image.

**Pull request merged**
