### PR TITLE
fix(ecs): add memory and cpu to container inputs

### PR DESCRIPTION
**Pull request by pkandasamy91**
Patching this fix into 1.18.x

### CODE REVIEW

**Comment by allisaurus** [comment]
@duftler  FYI - would we able to get this fix patched to 1.18.x ? (Thank you in advance!)

**Comment by duftler** [comment]
Yep. Once this one is merged we can get it cherry-picked.

**Comment by allisaurus** [comment]
@duftler  This was merged into master in https://github.com/spinnaker/deck/pull/7869 , but the auto cherry-pick there failed (not sure why, the content of the diff appears to be the same). 

Is it possible to add this to 1.18.x with this PR, or are there other steps we can take to patch this?

**Comment by duftler** [comment]
Ah, this is against `release-1.18.x` already. Sorry, didn't spot that.

**Comment by allisaurus** [comment]
No worries, thanks for your help!

**Pull request merged**
