### PR TITLE
(core): consolidate webpack configs

### PR DESCRIPTION
**Pull request by icfantv**
- move karma webpack config to main webpack
- update main webpack to account for test vs. prod modes

### CODE REVIEW

**Comment by icfantv** [comment]
@zanthrash @anotherchrisberry PTAL

**Comment by icfantv** [comment]
i'm investigating the build failure.  current thought is that it's a node issue.

**Comment by icfantv** [comment]
The issue is that the gradle build runs karma directly rather than running through npm which results in `ENV` not being set correctly in `webpack.config`.  There are several fixes:

1. have the gradle build set `ENV` to `test` and ensure the webpack config checks both the npm lifecycle event and the `ENV` environment variable, or
2. modify the gradle build to use `npm test` rather than running karma directly.

I've done number 1 (and will push the fix) but am open to thoughts/ideas.

@danielpeach forgot to tag you earlier.  PTAL.

**Comment by icfantv** [comment]
Ok, now it can't launch Chrome and I don't know why...

**Comment by icfantv** [comment]
Testing a new commit w/ option 2 above...

**Comment by icfantv** [comment]
Ok, that's failing locally with a weird error within the npm script.  looping in the dev prod team tomorrow.

**Comment by anotherchrisberry** [comment]
I like the idea behind this. It's a pain trying to maintain separate files that are largely duplicate code.

Another option to consider if getting the `ENV` set continues to be a challenge would be to extract the common bits into a single file, then compose and assemble them in `webpack.config.js` and `karma.conf.js`. I was doing something like that when working on modularizing the build (e.g. https://github.com/anotherchrisberry/deck/blob/lib-build/app/scripts/modules/docker/lib/webpack.config.js), using a base configuration, then adding and overriding the config based on the needs of each module.

**Comment by icfantv** [comment]
@anotherchrisberry @danielpeach @zanthrash went with option three to eliminate the node environment variable and extract the common functionality.  This results in a woefully puny webpack.config.js file but given that the config needs to be exported, I don't know that there's a way to eliminate it entirely.

**Comment by anotherchrisberry** [comment]
Nice! 👍

**Pull request merged**
