### PR TITLE
use configured timezone instead of hardcoded "PST"

### PR DESCRIPTION
**Pull request by anotherchrisberry**
cc @duftler @cfieber @sthadeshwar 

(don't merge until corresponding backend changes are in place)

### CODE REVIEW

**Comment by ajordens** [comment]
Where we at with this @anotherchrisberry?

**Comment by anotherchrisberry** [comment]
cc @duftler - did this get into whichever other service it was going into?

**Comment by duftler** [comment]
No, not yet. Hope to get back to this today or Monday.

**Comment by duftler** [comment]
The orca changes are here: https://github.com/spinnaker/orca/pull/791
Going to update the unified config to reflect the new properties next.
We should be good to merge this PR once that's done.

**Comment by duftler** [comment]
Config pr is here: https://github.com/spinnaker/spinnaker/pull/860

**Pull request merged**
