### PR TITLE
fix(ecs): angular is declared as global, so let's not redefine it

### PR DESCRIPTION
**Pull request by kevinawoo**

### CODE REVIEW

**Comment by christopherthielen** [comment]
FWIW, I'd rather we align all typescript code to use `import` and `export` style, i.e.: https://github.com/spinnaker/deck/blob/532ab7784ca93569308c8f2ab80a18d313b910f9/app/scripts/modules/amazon/src/serverGroup/details/scalingPolicy/createScalingPolicyButton.component.ts

**Comment by kevinawoo** [comment]
I thought I'd give it a try, but https://github.com/spinnaker/deck/blob/master/app/scripts/modules/ecs/src/ecs.module.ts#L39 I believe prevents me from doing that.

**Comment by christopherthielen** [comment]
Where it's being used, switch to `import { CREATE_SCALING_POLICY_BUTTON } from './path/to/file'`, like so: 

https://github.com/spinnaker/deck/blob/master/app/scripts/modules/ecs/src/ecs.module.ts#L8

**Comment by kevinawoo** [comment]
OH man, I derped hard on that, Thanks! It's been a while since I've been in actually js/ts app code -_-"

**Pull request merged**
