### PR TITLE
feat(core): updated notifications to react-toastify

### PR DESCRIPTION
**Pull request by ranihorev**
API changes: 
- Removed the `body` option as it wasn't in use (verify that)
- Added an `options` field for react toastify option

image

### CODE REVIEW

**Comment by caseyhebebrand** [comment]
Curious what the reasoning is for adding `react-toastify`? For me the benefits seem neutral. We are cleaning up some lines of code, but also adding a new package.

Also, while you are in the `Notifier`, could you make it a functional component? The `useObservable` hook in deck is great for subscription lifecycles.

**Comment by ranihorev** [comment]
The current notifications are hiding the new help menu on the bottom left.
Chris also mentioned that it could be useful for some of his features.

I was trying to minimize the changes. If I need to make more substantial
changes, I can remove this component completely as the subscription service
is not needed anymore.

**Comment by caseyhebebrand** [comment]
> The current notifications are hiding the new help menu on the bottom left. Chris also mentioned that it could be useful for some of his features. 

Ok great. That makes sense, I am happy to hear it will be leveraged more. It sounds like the benefits outweigh the costs 👍🏼 

> I was trying to minimize the changes. If I need to make more substantial changes, I can remove this component completely as the subscription service is not needed anymore.

My opinion is that we should get rid of that if we know that the subscription service isn't needed to remove some tech debt.

**Comment by ranihorev** [comment]
> My opinion is that we should get rid of that if we know that the subscription service isn't needed to remove some tech debt.

Good call :)
I removed it. It's much simpler now

**Review by caseyhebebrand — APPROVED** [review]
LGTM - thanks for cleaning up the notifier service!

**Pull request merged**
