### PR TITLE
fix(provider/kubernetes): Change FileSystem to Filesystem

### PR DESCRIPTION
**Pull request by tpayne1**
This addresses issue: #2993. The problem is that deck pushes `FileSystem` and cloud driver expects `Filesystem`. This causes the pod yamls to not be updated and thus the deployed state to not reflect state as displayed in deck.

### CODE REVIEW

**Comment by ethanfrogers** [comment]
spinnaker/spinnaker#2993

**Comment by lwander** [comment]
@spinnakerbot cherry-pick 1.10

**Comment by lwander** [comment]
@spinnakerbot cherry-pick 1.10

sorry for the noise :)

**Comment by ethanfrogers** [comment]
`sudo cherry-pick 1.10` 🤣

**Pull request merged**
