### PR TITLE
core/bake: Add support for 'varFileName' attribute to bake stages.

### PR DESCRIPTION
**Pull request by duftler**

### CODE REVIEW

**Comment by duftler** [comment]
Adds support for Google, Amazon and Azure.

**Comment by duftler** [comment]
Relates to https://github.com/spinnaker/orca/pull/944 and https://github.com/spinnaker/rosco/pull/131, but they can be merged in any order.

**Comment by duftler** [comment]
Looks the same on all 3 of those platforms:
image

**Comment by duftler** [comment]
@anotherchrisberry or @zanthrash Can you please eyeball this? It touches several providers.

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
