### PR TITLE
Manual Judgment support for `propagateAuthenticationContext`

### PR DESCRIPTION
**Pull request by ajordens**
image

image

image

### CODE REVIEW

**Comment by ajordens** [comment]
Supported this on the backend for awhile ... this PR just adds it to the UI (_prompted by an internal user who wanted to do it_).

Wording might be off but it's largely self explanatory from the few internals I've talked to.

PTAL @anotherchrisberry

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by tomaslin** [comment]
might be tangential, but don't believe we pass down this authentication context to bake stages which doesn't reset bake user

**Comment by ajordens** [comment]
@tomaslin Ya, that would be something orthogonal to this ... feel free to cut an issue and I'll update the bake stage in `orca` such that it's a little smarter around where it looks for auth (_it's bake stage looking up vs. it being provided to the bake stage_).

**Pull request merged**
