### PR TITLE
feat(core/visualizer): Allow visualizer toggle from URL query param `?vis=true`

### PR DESCRIPTION
**Pull request by christopherthielen**
The visualizer can be useful to diagnose problems.  By adding a url trigger, we can share links with the visualizer enabled.

### CODE REVIEW

**Comment by jrsquared** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
LGTM. While you're in there, can you add similar functionality to enable trace logging on transitions? A surprising number of folks open the console when they're having trouble and get confused by all the messages.

**Comment by christopherthielen** [comment]
I haven't merged this yet because the `?vis=true` is being added to the "Recent Application"

screen shot 2017-05-10 at 11 06 19 am

**Comment by christopherthielen** [comment]
OK, I've updated this, adding support for:
`?trace=true` or `trace=all` or `trace=TRANSITION,UIVIEW,VIEWCONFIG`, etc

I've also adjusted the "save recent places" code to ignore `trace`, `debug`, and `vis` parameter values.

**Pull request merged**
