### PR TITLE
(cf) Fine tune clone server group bits

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Comment by gregturn** [comment]
@spinnaker/reviewers

**Comment by gregturn** [comment]
Depends on https://github.com/spinnaker/clouddriver/pull/1225

**Comment by danielpeach** [comment]
LGTM

**Comment by gregturn** [comment]
@spinnaker/reviewers Rebased. PTAL

**Comment by gregturn** [comment]
@anotherchrisberry Got time for this one too?

**Comment by gregturn** [comment]
@anotherchrisberry Rebased.

**Pull request merged**
