### PR TITLE
feat(core): convert to ng1/ng2 hybrid app

### PR DESCRIPTION
**Pull request by icfantv**
* contains only the performance improvements as developed with
misko and rob.  a subsequent PR will wire in the testing changes
discussed as well as the original conversion items from the previous
hybrid PR that was backed out.

### CODE REVIEW

**Comment by icfantv** [comment]
@jrsquared PTAL
@anotherchrisberry not sure what time your flight leaves today, but would love your eyes on this if you have any free time, but totally understood if you don't.

**Comment by anotherchrisberry** [comment]
Are the commented out sections of code potentially going away, or just temporarily commented out?

I just cut a release, so there's a good spot to back out if there are issues with the hybrid app (or if the performance changes I made have issues). I'd say let's merge this and get it out and see how it goes.

**Comment by icfantv** [comment]
Just temporarily commented out.  I wanted a baseline release with nothing but the bootstrap and performance tweaks to isolate everything.

I'll rebase and merge this now.

**Comment by icfantv** [comment]
@anotherchrisberry rebased and waiting for CI to finish.  I have to step out for a while.

**Pull request merged**
