### PR TITLE
allow pipelines to be explicitly turned off

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Allows pipeline functionality to be disabled by setting the feature flag to `false`.

@ajordens please review

### CODE REVIEW

**Comment by ajordens** [comment]
LGTM

**Comment by tomaslin** [comment]
should probably also hide custom deployment strategies if this flag is on

**Comment by anotherchrisberry** [comment]
@tomaslin good point, will update

**Comment by anotherchrisberry** [comment]
added a commit to restore the angular-wizard css, since there are still one or two old wizards lurking around in the codebase

**Pull request merged**
