### PR TITLE
fix(amazon/subnet): fix NPE when AWSProviderSettings.serverGroups is undefined

### PR DESCRIPTION
**Pull request by christopherthielen**

### CODE REVIEW

**Review by caseyhebebrand — APPROVED** [review]

**Comment by zachsmith1** [comment]
@caseyhebebrand can we add a test and then add this as a backport candidate for 1.25.x? 

regression PR: https://github.com/spinnaker/deck/pull/8901

**Comment by zachsmith1** [comment]
@spinnakerbot add-label backport-candidate

**Comment by zachsmith1** [comment]
Notes for backport: documented regression above. If a test is absolutely required for this specific instance please reach out to myself or @caseyhebebrand.

**Comment by link108** [comment]
@mergifyio backport release-1.25.x

**Pull request merged**
