### PR TITLE
fix(provider/aws): Pre-populate spot price field with ancestor value …

### PR DESCRIPTION
**Pull request by duftler**
…on clone. Send '' instead of null when no spot price is requested.

### CODE REVIEW

**Comment by duftler** [comment]
Relates to: https://github.com/spinnaker/clouddriver/pull/1908

**Comment by duftler** [comment]
Unit test failed. Looking...

**Comment by duftler** [comment]
@tanelso2

**Comment by tanelso2** [comment]
:+1: Looks good! Thanks!

**Pull request merged**
