### PR TITLE
fix(kubernetes): Allow resource name to be added as expression

### PR DESCRIPTION
**Pull request by maggieneterval**
…e can be entered as an expression

Resolves: https://github.com/spinnaker/spinnaker/issues/3513

### CODE REVIEW

**Comment by christopherthielen** [comment]
@gcomstock PTAL

**Comment by maggieneterval** [comment]
Played around with it a little more and pushed a change to clarify existing Creatable select functionality rather than adding the text/select toggle:

creatable

@gcomstock I defer to your design sensibilities :)

**Comment by christopherthielen** [comment]
@maggieneterval I didn’t mean that you should not merge as is. I wanted Greg to use this as a real world example. We’ve been discussing how to handle expressions all across spinnaker and this is a good data point.

**Comment by maggieneterval** [comment]
@christopherthielen I didn't realize how the Creatable component worked so I think the second fix is cleaner for now. But curious what we land on regarding handling expressions across Spinnaker as a whole!

**Comment by gcomstock** [comment]
Thanks for tagging me on this! Sorry I didn't catch it Friday. I did some early work on how we might validate/render expressions in spinnaker here:

https://gallery.io/projects/MCHbtQVoQ2HCZcM1NWkzJjWA/files/MCGgtPMLb5Pry9LxMg_LJ1em

In the case of a dropdown + ability to use a custom expression, let me add this use case to the form field design deck tomorrow. I'll share it in the OSS spinnaker channel as soon as I put it in. I don't think there's anything wrong with merging this now though. Thanks for asking me!

**Comment by maggieneterval** [comment]
@gcomstock Looks great, thanks for putting that together!

**Comment by maggieneterval** [comment]
@danielpeach Would it be possible to include this with 1.10.4? This issue is a blocker for the user who posted the issue

**Comment by gcomstock** [comment]
Here’s a few different options for how a key can take either a predefined values or a custom expression. Please share your thoughts on the slide at your convenience: https://gallery.io/projects/MCHbtQVoQ2HCZcM1NWkzJjWA/files/MCHtA7U1iMGr6xG3sIbzweygP8eVUeK21tE

**Comment by maggieneterval** [comment]
Thanks @gcomstock, this is great. I like options A and B, especially the use of the `${*}` icon to identify all expression-enabled inputs.

**Pull request merged**
