### PR TITLE
fix(aws/lambda): Shows function details and actions menu.

### PR DESCRIPTION
**Pull request by rvazquezglez**
fix(aws/lambda): Shows function details and actions menu.

Lambda details were not loading, this PR fixes this issue:
image

Stacktrace:
```
TypeError: Cannot destructure property 'application' of 'this.state' as it is null.
    at FunctionActions_FunctionActions.render (https://preprod.spinnaker.armory.io/3.js:112515:203011)
    at gi (https://preprod.spinnaker.armory.io/3.js:222406:192)
    at fi (https://preprod.spinnaker.armory.io/3.js:222405:224)
    at Rj (https://preprod.spinnaker.armory.io/3.js:222487:490)
    at Qj (https://preprod.spinnaker.armory.io/3.js:222470:265)
    at Kj (https://preprod.spinnaker.armory.io/3.js:222470:194)
    at yj (https://preprod.spinnaker.armory.io/3.js:222463:172)
    at https://preprod.spinnaker.armory.io/3.js:222347:115
    at push.exports.unstable_runWithPriority (https://preprod.spinnaker.armory.io/3.js:222554:467)
 ```

### CODE REVIEW

**Review by zachsmith1 — APPROVED** [review]
LGTM

**Comment by rvazquezglez** [comment]
@spinnakerbot add-label backport-candidate

**Comment by zachsmith1** [comment]
@Mergifyio backport release-1.26.x release-1.25.x release-1.24.x

**Comment by rvazquezglez** [comment]
@Mergifyio backport release-1.23.x

**Pull request merged**
