### PR TITLE
feat(aws): Add the cloudformation stage UI

### PR DESCRIPTION
**Pull request by xavileon**
This patch introduces a first iteration of the cloudformation UI
component. It was heavily based on the kubernetes deploy manifest
stage. It allows the user to specify a cloudformation stage by picking
the necessary information: account, region, template (artifact or
embedded) and parameters.

screen shot 2019-02-08 at 21 58 42

Related issue: https://github.com/spinnaker/spinnaker/issues/736

### CODE REVIEW

**Comment by jervi** [comment]
@spinnaker/reviewers PTAL

**Comment by sbwsg** [comment]
Just to confirm - does the 👍 mean you tested it and everything was ok or just ACKing my comment?

**Comment by xavileon** [comment]
sorry, I wasn't clear :sweat_smile: I was ACKing your comment, I will ping you once I've tested it with the updated head.

**Comment by sbwsg** [comment]
awesome, cheers!

**Comment by xavileon** [comment]
hi @sbwsg I had the chance to test with the latest head in all services and it works as expected! so feel free to merge 🙂

**Comment by yrathams1990** [comment]
@xavileon xavileon Does the spinnaker pipeline stage "deploy CloudFormation” accept user provided parameters file ( it can be via the spinnaker pipeline script ). I see that we can pass the parameters in this stage on the spinnaker console.

**Pull request merged**
