### PR TITLE
fix(aws): Fix userData getting lost when cloning an AWS server group that uses launch templates (#6771)

### PR DESCRIPTION
**Pull request by ashleykleynhans**
Fixes issue [6771](https://github.com/spinnaker/spinnaker/issues/6771).

deck-fix

### CODE REVIEW

**Comment by dbyron-sf** [comment]
@ashleykleynhans can you run `yarn prettier` please?

**Comment by ashleykleynhans** [comment]
@dbyron-sf apologies for that, its been done now.

**Comment by dbyron-sf** [comment]
@ashleykleynhans No worries at all!  Thank you for the fix!

**Comment by dbyron-sf** [comment]
Not sure many of these we'll actually release, but let's at least get the branches in shape.

**Pull request merged**
