### PR TITLE
fix(core/serverGroup): Correct 'simple scaling' heuristic

### PR DESCRIPTION
**Pull request by danopia**
This was seemingly introduced from 6630f9bca7bd17e99bafa174b7659bc6c63f79fd ( [original aws-specific line](https://github.com/spinnaker/deck/commit/6630f9bca7bd17e99bafa174b7659bc6c63f79fd#diff-3c78280adb08436113301d7b7626cb0aL18), [new generalized line](https://github.com/spinnaker/deck/commit/6630f9bca7bd17e99bafa174b7659bc6c63f79fd#diff-75e228042e668327134e67ca85b78996R14) )

The regression is that the "Capacity" section always considers the scaling mode to be "simple", and doesn't show the actual min/max capacity numbers, only Desired. Selecting the "Resize Server Group" function still displays correct numbers in its dialog, as shown below.

Screen Shot 2019-09-11 at 10 25 34 AM

Noticed using an AWS account.

### CODE REVIEW

**Comment by danopia** [comment]
I built this branch into an artifact and gave it to Halyard. Looks good from here:

Screen Shot 2019-09-18 at 2 51 36 PM

@spinnaker/reviewers

**Comment by avram** [comment]
@spinnakerbot add-tag @spinnaker/reviewers

**Comment by avram** [comment]
@spinnakerbot add-label provider/aws

**Comment by ethanfrogers** [comment]
@christopherthielen PTAL

**Comment by kevinawoo** [comment]
hey hey @danopia and @avram would you be able to write a test so hopefully no one regresses it again 😞

**Pull request merged**
