### PR TITLE
(core) adds logout button

### PR DESCRIPTION
**Pull request by danielpeach**
@anotherchrisberry @icfantv adds log out button.

Looks like this:
logout

### CODE REVIEW

**Comment by icfantv** [comment]
LGTM, but since NF doesn't use this functionality, I'm going to defer to @anotherchrisberry.

As far as L&F goes, if you envision more account-level menu items then I would say a menu is fine.  But if it's only ever going to be Log Out, you might consider just putting button next to the user name to keep it simple and visible.  Just my two cents.

**Comment by anotherchrisberry** [comment]
Agree with what @icfantv said. I imagine we'll include more in the menu someday, so this is fine by me.

**Comment by ttomsu** [comment]
Can you also confirm it will appear when the window width is smaller? I usually see an online of a head, with a pointer cursor when hovering that doesn't do anything on click.

re: NFLX doesn't use this feature: You may want it when Fiat comes online.

**Comment by danielpeach** [comment]
@ttomsu updated / fixed the user menu for small window widths.

small_user_menu

**Comment by ttomsu** [comment]
Awesome! Thank you!

**Comment by danielpeach** [comment]
Closes https://github.com/spinnaker/spinnaker/issues/1363

**Pull request merged**
