### PR TITLE
fix(gremlin): Check for fetched data from API

### PR DESCRIPTION
**Pull request by zslabs**
Amendment to https://github.com/spinnaker/deck/pull/6549

Validates we have both `commands` and `targets` returned from API before populating Summary panel on revisit.

cc @anotherchrisberry @mattrjacobs

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Looks good - can you maybe squash the commits and, while you're doing that, update the commit message to the format the bot is barking about?

**Comment by zslabs** [comment]
👋 @anotherchrisberry Sorry for the delay on this one. I've squashed all my commits and this one is ready for review. Thanks again!

**Comment by anotherchrisberry** [comment]
This looks good to me - can you squash this PR one more time and change the commit message to the title of this PR (`fix(gremlin): Check for fetched data from API`)?

**Comment by zslabs** [comment]
👌 Let me know if this looks good! 🤞

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
