### PR TITLE
feat(gremlin): Gremlin UI which takes API key input then fetches comm…

### PR DESCRIPTION
**Pull request by mattrjacobs**
…and/target templates for further selection

Credit to @zslabs for all of this work - coming from my account as I rebased it all to make review easier.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
See review comments on https://github.com/spinnaker/deck/pull/6547

**Comment by zslabs** [comment]
Hey @anotherchrisberry thanks for taking a look at this! Could you expand a bit more on https://github.com/spinnaker/deck/pull/6547#discussion_r256960041 -- what all of the settings files I'll need to update are?

I've pushed a commit with the other items you mentioned. Thanks again!

**Comment by anotherchrisberry** [comment]
Great, thanks! I think there are two settings.js files you'll want to update:
- in the root directory ([/settings.js](https://github.com/spinnaker/deck/blob/master/settings.js))
- in the halconfig directory ([/halconfig/settings.js](https://github.com/spinnaker/deck/blob/master/halconfig/settings.js))

**Comment by zslabs** [comment]
Gotcha! Just pushed an update with the feature flag added in.

**Pull request merged**
