### PR TITLE
fix(bake): make helm chart file path visible when the chart comes fro…

### PR DESCRIPTION
**Pull request by dbyron0**
…m a git/repo artifact

original issue: https://github.com/spinnaker/spinnaker/issues/5249

Thanks to @christopherthielen for the very big push here.

### CODE REVIEW

**Comment by dbyron0** [comment]
@fieldju Please cherry pick this to the 1.24 release branch.  It fixes a new feature in 1.24: https://spinnaker.io/community/releases/next-release-preview/#bake-helm-charts-using-gitrepo-artifacts.  Thanks much!

**Comment by dbyron0** [comment]
@spinnakerbot add-label backport-candidate

**Comment by fieldju** [comment]
@Mergifyio backport release-1.24.x

**Comment by fieldju** [comment]
Okay, doing: https://spinnaker.io/community/releases/release-manager-runbook/#audit-backport-candidates will get this in today's patch release.

**Pull request merged**
