### PR TITLE
(core): normalize app builder module

### PR DESCRIPTION
**Pull request by icfantv**

### CODE REVIEW

**Comment by icfantv** [comment]
@anotherchrisberry @zanthrash PTAL

**Comment by anotherchrisberry** [comment]
LGTM - note @danielpeach this PR also normalizes the module export for `gceSessionAffinityFilter`

**Comment by anotherchrisberry** [comment]
Looks like this is superseded by https://github.com/spinnaker/deck/pull/3087, right?

**Comment by icfantv** [comment]
I broke it up into several PRs because this one was fairly large and I didn't know how big #3087 would be.  #3087 is the rest of the conversions, this one was just the app builder module.

**Comment by anotherchrisberry** [comment]
#3087 seems to include all of these changes.

**Comment by icfantv** [comment]
oh crap, i bet i branched off the wrong branch.

**Comment by icfantv** [comment]
i'm going to merge 3087 first and then see where this is at.

**Comment by icfantv** [comment]
Yep, not exactly sure what happened here.  Closing.  DO NOT MERGE.

**Pull request closed without merging**
