### PR TITLE
Updating email validation to allow for longer domains per issue-6636

### PR DESCRIPTION
**Pull request by ssnorrizaurous**
Updating email validation to allow for longer domains per [issue-6636](https://github.com/spinnaker/spinnaker/issues/6636)

### CODE REVIEW

**Review by mattgogerly — COMMENTED** [review]
Does it make sense to use a proper email Regex such as one from https://emailregex.com? Rather than just fixing this specific issue.

**Comment by ssnorrizaurous** [comment]
> Does it make sense to use a proper email Regex such as one from https://emailregex.com? Rather than just fixing this specific issue.

@mattgogerly makes sense to me. I updated the regex to match the site and initialize it as a const instead of on the fly.

**Comment by mattgogerly** [comment]
@ssnorrizaurous mind running spotless:apply to fix the lint error?

**Comment by mattgogerly** [comment]
@Mergifyio update

**Pull request merged**
