### PR TITLE
Upgraded Node version.  …

### PR DESCRIPTION
**Pull request by vjames-bmc**
Upgraded Node version. Also changed npm version to 2.14 since that is the npm version that goes with node 4.4
(see http://nodejs.org/en/download/releases)

### CODE REVIEW

**Comment by vjames-bmc** [comment]
Looks like Travis doesn't support node 4.4. Is there a way we could add that ? (https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against)

**Comment by anotherchrisberry** [comment]
From reading that travis link, it might be fine if you update the `.travis.yml` file for deck. nvm supports v4.4.0 and v4.4.1. Then again, I don't know what happens when you change the language from `java` to `javascript`... will it even build?

It's worth trying. I'd be happy to play around with it but my computer is dying every five minutes so I'll be lucky if I can even get this comment posted, much less create a branch in Git!

**Comment by tomaslin** [comment]
please also update the dockerfile dependency if we're changing this

**Comment by tomaslin** [comment]
https://github.com/spinnaker/deck/blob/master/Dockerfile#L1

**Comment by vjames-bmc** [comment]
I was on vacation last couple of days. Will try it this week.

**Comment by vjames-bmc** [comment]
@anotherchrisberry I changed node version to 4.4.1 and it is OK now. Travis was looking for the node file by verson 4.4 before and couldn't find it. The file name is *4.4.1* .

**Comment by anotherchrisberry** [comment]
Tested locally with 4.4.1 and had no problem - thanks!

**Pull request merged**
