### PR TITLE
(core) add analytics to alerts/notices, update icons

### PR DESCRIPTION
**Pull request by anotherchrisberry**
* changing notices to flag icons, alerts to the yellow-orange color
* adding analytics to tag hover events

### CODE REVIEW

**Comment by icfantv** [comment]
I wonder if it makes sense to add a `location` property to the component so we can track which tags are actually being used/used the most.  This is something Archana was asking about and interested in.

**Comment by icfantv** [comment]
Otherwise, LGTM.

**Comment by anotherchrisberry** [comment]
Ah, yeah, that makes sense - include account and region?

**Comment by icfantv** [comment]
Sorry, I meant location on the page, e.g., ASG level vs. Tab level vs. etc...  What were you thinking?

**Comment by anotherchrisberry** [comment]
That makes sense - I'll add that to the label. I was talking about adding account/region to help distinguish between identically named components (gonna do that, too)

**Comment by icfantv** [comment]
Oh yea.  That's good too.

**Pull request merged**
