### PR TITLE
provider/openstack: Added pipeline destroy server group stage

### PR DESCRIPTION
**Pull request by derekolk**
close https://github.com/spinnaker/spinnaker/issues/1126

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM - does anyone else need to review it or should I go ahead and merge it?

**Comment by derekolk** [comment]
@jcwest PTAL

**Comment by jcwest** [comment]
LGTM

**Comment by derekolk** [comment]
@spinnaker/reviewers

**Pull request merged**
