### PR TITLE
provide svg logo for cloud foundry

### PR DESCRIPTION
**Pull request by anotherchrisberry**
@gregturn can you try this out - trying to get a nice logo for server groups in CloudFoundry like we have for AWS and GCP, e.g.
screen shot 2016-02-01 at 1 34 31 pm

### CODE REVIEW

**Comment by gregturn** [comment]
Looks nice, except that's not the right logo. Checkout https://www.cloudfoundry.org/foundation/style-guide/ and you'll find that late last year, they came out with a new image called "molten". You can use just the icon without "CloudFoundry" wrapped around it. Sorry!

**Comment by anotherchrisberry** [comment]
No worries - I'm confused - is CloudFoundry (CF) different from Pivotal CloudFoundry (PCF)? I am wondering if we're branding this right - seems like PCF is an implementation or hosted version of CF. Are you building a generic CF module or is it explicitly written for PCF?

Sorry, I am not very familiar with the whole CF ecosystem!

**Comment by gregturn** [comment]
PCF is Pivotal's commercialed version. 
PWS is our public cloud version of PCF. 
CF is an open source project with its own foundation. 

I've coded things to talk to any compliant version of CF (even IBM's bluemix) so I suggest using CF foundations logo.

**Comment by anotherchrisberry** [comment]
Awesome, that's good news. I'll get an SVG together of the CF logo and update this PR.

**Comment by anotherchrisberry** [comment]
Our designer is reaching out to the CF team for guidance on appropriate usage of the logo (and hopefully to get a good SVG for the icon) - going to close this for now and re-open once we get something.

**Pull request closed without merging**
