### PR TITLE
refactor(*): remove unused local storage caches

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Backend performance has improved pretty dramatically since the Spinnaker project started over four years ago. Many calls that were very slow and fairly expensive then no longer are, and things we used to cache in local storage don't really need to be.

Some of those entities (load balancers, instance types) are things we haven't cached for over a year. Some of them are actually pretty small or come back really quickly (VPCs/networks, subnets), so we really don't need to cache them.

Some things (really just applications) we used to cache because they were the landing page, but now search is the default landing page - and the applications list can be really big, so we shouldn't call it unless we need the data IMO.

The only thing we really need to cache IMO is security groups, and in almost every place where they are read, we provide a link to refresh the cache. So we can get rid of the entire section in the Application Config view, which is better, anyway, since those caches are not specific to the application (we just didn't have a better place to handle it).

There are a handful of other caches that seem like they don't need to be caches, and they are all in GCE: addresses, certificates, healthChecks. I don't know enough about those calls or spots in the code to feel comfortable removing them, but if @maggieneterval or @sbwsg or @louisjimenez have time to take a look (search for `InfrastructureCaches.get('addresses')` etc to see the usage), I think it'd be nice to remove them, and then do a bigger refactor of the whole InfrastructureCaches bit.

Also worth pulling this down and confirming everything still works on kubernetes (and other providers). I've tested on AWS and it all seems fine.

### CODE REVIEW

**Comment by archana-s** [comment]
Didn't realize it would clean up so much! Thanks for doing this.

**Comment by maggieneterval** [comment]
Wow, what an amazing cleanup! I will pull this down and run through some k8s workflows now, will give the thumbs up once I'm done. Thanks a bunch @anotherchrisberry!

**Comment by maggieneterval** [comment]
And regarding the GCE cleanup, I made a ticket so we don't forget to do this at some point: https://github.com/spinnaker/spinnaker/issues/4102
:smile:

**Comment by anotherchrisberry** [comment]
Awesome, thank you for taking a look @maggieneterval! I cleaned up that unused import and will get this merged.

**Pull request merged**
