### PR TITLE
feat(core): replace stage-specific feature flags with hiddenStages setting

### PR DESCRIPTION
**Pull request by maggieneterval**
Replaces each instance of a stage-specific feature flag with a single `hiddenStages` setting to register a list of stage keys that should not be exposed to end users.

* feat(core): remove gremlin, travis, wercker, and infrastructureStages feature flags

  Removes each stage-specific feature flag.

* feat(core): add hiddenStages setting

  Adds `spinnakerSettings.hiddenStages` so that a list of stage keys to be omitted from the registry can be set in `settings-local.js`. (We will not expose a Halyard command for this, since the initial goal of this change is to reduce the number of feature flags we expose in Halyard).

I will communicate this change in the 1.20 release notes, and update spinnaker.github.io to reflect the removal of these feature flags, which are currently referenced in at least the Travis and Wercker setup pages.

### CODE REVIEW

**Comment by christopherthielen** [comment]
I can't recall.  Do we have another mechanism to show/hide stages in the UI? I know at netflix we do not want to expose these to our users.

**Comment by maggieneterval** [comment]
@christopherthielen Thanks for letting me know! Hmm, do you have a sense for whether hiding these stages by default will be what most organizations want? If yes, then I'm happy to close this. If not, how would you feel about flags to disable these stages rather than enable them? It seems a little arbitrary to have just these three stages opt-in-by-flag, but not, for example, the Jenkins stage.

**Comment by anotherchrisberry** [comment]
At some point, there was discussion around moving Gremlin/Travis/Wercker/Jenkins/etc. out of core and into their own NPM packages, e.g. `@spinnaker/gremlin`, `@spinnaker/travis`. 

I don't know if that's still under consideration, but would allow Netflix to not show them (we just wouldn't include the packages in our custom build), while still showing them in the default OSS build.

Obviously it's a lot more work than what's involved in this PR!

**Comment by christopherthielen** [comment]
>  It seems a little arbitrary to have just these three stages opt-in-by-flag, but not, for example, the Jenkins stage.

completely agree!  

What do ya'll think about dropping the individual feature flags for these stages and adding a new setting like `hiddenStages` that either removes stages from the registry or from the dropdown?  We could give `triggers` the same treatment.

**Comment by maggieneterval** [comment]
Love the idea of a new `hiddenStages` setting! Will add that as a second commit on this PR and re-tag y'all when it's ready for another look.

**Comment by maggieneterval** [comment]
@anotherchrisberry @christopherthielen This is ready for another pass whenever, many thanks! 😄

**Pull request merged**
