### PR TITLE
fix(artifacts): Fix fetching helm artifact versions

### PR DESCRIPTION
**Pull request by eromanova**
issue: https://github.com/spinnaker/spinnaker/issues/4370

### CODE REVIEW

**Comment by dbyron0** [comment]
Any chance to cherry pick this to 1.13 (and even 1.12 if it applies there)?  Thx.

**Comment by maggieneterval** [comment]
@spinnakerbot cherry-pick 1.14

**Comment by maggieneterval** [comment]
@spinnakerbot cherry-pick 1.13

**Comment by dbyron0** [comment]
Thanks @maggieneterval !

**Pull request merged**
