### PR TITLE
changing from floating ip to network because of back end change

### PR DESCRIPTION
**Pull request by emjburns**
Small naming change for floating ip -> network

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM - does anyone else need to review before I merge this?

**Comment by emjburns** [comment]
@anotherchrisberry Nope - @jcwest worked on it with me so it's all reviewed from my end.

**Comment by anotherchrisberry** [comment]
Looks like a test broke...

**Comment by emjburns** [comment]
Ya... I'll fix it tomorrow morning. Sorry.

**Comment by emjburns** [comment]
@anotherchrisberry Fixed! Merge whenever :)

**Pull request merged**
