### PR TITLE
Corrects issues in Dockerfile related to relative path expectations o…

### PR DESCRIPTION
**Pull request by ttomsu**
…f apache scripts

@aarondobbing @dforrest88 FYI

### CODE REVIEW

**Comment by ttomsu** [comment]
Related discussion for onlookers: https://github.com/spinnaker/deck/pull/3280

**Comment by ttomsu** [comment]
Verified by building and deploying locally. Here's the output from my container:

```
2017-02-09T18:21:03.693025994Z Stopping web server: apache2.
2017-02-09T18:21:03.734506727Z Considering dependency setenvif for ssl:
2017-02-09T18:21:03.734551170Z Module setenvif already enabled
2017-02-09T18:21:03.734569170Z Considering dependency mime for ssl:
2017-02-09T18:21:03.734574410Z Module mime already enabled
2017-02-09T18:21:03.734578602Z Considering dependency socache_shmcb for ssl:
2017-02-09T18:21:03.734582963Z Enabling module socache_shmcb.
2017-02-09T18:21:03.740323676Z Enabling module ssl.
2017-02-09T18:21:03.740345820Z See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
2017-02-09T18:21:03.743560791Z To activate the new configuration, you need to run:
2017-02-09T18:21:03.743578308Z   service apache2 restart
2017-02-09T18:21:03.798203940Z Enabling site spinnaker.
2017-02-09T18:21:03.801603437Z To activate the new configuration, you need to run:
2017-02-09T18:21:03.801623234Z   service apache2 reload
2017-02-09T18:21:03.979271384Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using <ip address>. Set the 'ServerName' directive globally to suppress this message
```

**Comment by ttomsu** [comment]
Did this fix the issue you guys were seeing?

**Comment by aarondobbing** [comment]
Havent tried from this build, i see no reason why it wont - I will be able to test properly tomorrow if you like.

**Comment by dforrest88** [comment]
I just pulled down the master tag and things look to be back to normal. Thanks for turning this fix around!

**Pull request merged**
