### PR TITLE
feat(core): add label filter UI to clusters view

### PR DESCRIPTION
**Pull request by maggieneterval**
Closes https://github.com/spinnaker/spinnaker/issues/3238:

6a78d305-cc3e-4e77-ab7c-1103d4d6459e

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Which cloud providers support labels?

If it's only Kubernetes, I'd suggest not showing this unless an app is configured with Kubernetes as a cloud provider - or maybe hide it if there are no labels in any of the server groups, if that's easier.

**Comment by maggieneterval** [comment]
@anotherchrisberry Good idea, just updated to hide the Labels section if none of the server groups have labels. [This change](https://github.com/spinnaker/clouddriver/pull/3070/files) allows all infrastructure objects regardless of provider to have labels but I think only Kubernetes currently uses them.

**Comment by duftler** [comment]
GCE server groups have labels:
image

**Comment by maggieneterval** [comment]
Oh nice, thanks @duftler!

**Pull request merged**
