### PR TITLE
fix(buildStatus): Change Deck CI to Branch Build to align with the re…

### PR DESCRIPTION
**Pull request by ttomsu**
…st of the repos

It appears these GHActions are much more integrated, and it's unclear which reference _Actions_ named "Deck CI" and which reference _Jobs_ named "Deck CI". I *think* most of them reference _job names_, but I'm not 100% certain.

This change goes along with https://github.com/spinnaker/spinnaker.github.io/pull/1823

### CODE REVIEW

**Comment by ttomsu** [comment]
That's correct - the Build Status page uses the _Action_ name, and this PR changes that name to the same name all the other repos use ("Branch Build").

However, this repo does far more things with Actions, and happens to have a *Job* named "Deck CI" as well. I haven't changed any other places that reference this _Job_ name, as I think that's what the other tools use, like Mergify.

**Comment by maggieneterval** [comment]
@ttomsu, gotcha. Should we verify that's the case by attempting to use the `ready to merge` label on this PR?

**Comment by ttomsu** [comment]
SGTM

**Comment by christopherthielen** [comment]
The *Job* named 'Deck CI' is what Deck's branch protection will block on.  It is a meta-job that depends on all the other jobs passing.

**Pull request merged**
