### PR TITLE
(core) use HappyPack plugin to speed up local builds

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Playing around with https://github.com/amireh/happypack and finding it speeds up local builds quite a bit (from ~60s to ~15s).

Curious if it plays well with Travis or makes any difference...let's find out!

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@zanthrash @icfantv PTAL

**Comment by anotherchrisberry** [comment]
Note: the HappyPack project doesn't seem to have a license, so probably not a great idea to merge this (even if it's awesome and makes local development a lot faster) until the project does include a license.

**Comment by icfantv** [comment]
This would be amazing.  [Linking in](https://github.com/amireh/happypack/issues/73) @anotherchrisberry's issue.

**Comment by amireh** [comment]
FWIW, you might get better results if you use a shared thread pool since you have 3 plugin instances. I would try it out before committing to this. Here's an example for your config:

```javascript
var HappyPack = require('happypack');
var happyThreadPool = HappyPack.ThreadPool({ size: 4 }); // experiment with this

// ...
plugins: {
  // ...
  new HappyPack({
    id: 'js',
    loaders: [ 'ng-annotate!angular!babel!envify!eslint' ],
    threadPool: happyThreadPool,
  }),

  new HappyPack({
    id: 'html',
    loaders: [ 'ngtemplate?relativeTo=' + (path.resolve(__dirname))  + '/!html' ],
    threadPool: happyThreadPool,
  }),

  new HappyPack({
    id: 'less',
    loaders: [ 'style!css!less' ],
    threadPool: happyThreadPool,
  }),
   // ...
}
```

Glad it's working out for you! You should have no problems with licensing, it's already MIT licensed and I've added it to the docs.

**Comment by anotherchrisberry** [comment]
Awesome, thanks @amireh - the threadpool does seem to speed up initial build quite a bit!

**Pull request merged**
