### PR TITLE
refactor(core): De-angular pipelineConfig.service

### PR DESCRIPTION
**Pull request by jrsquared**

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Is there any reason this needs to be on another object and can't be a singleton with static methods?

**Comment by jrsquared** [comment]
Not really... the view state cache is stored locally, but that could be static too. Yeah, I'll make it static.

**Comment by jrsquared** [comment]
Happy now @anotherchrisberry

**Comment by anotherchrisberry** [comment]
Yes

**Pull request merged**
