### PR TITLE
Upgrade to Angular 1.5.0

### PR DESCRIPTION
**Pull request by zanthrash**
Adding a decorator around ui-select-match and ui-select-choices directives to insert the a class on the template with the directives name.  This is to get around the fact that ui-select is pretty much abandonware an that it doesn't seem to play nicely with Angular 1.5.0's lazy compilation and/or it's new multiple transclustion feature.

@duftler @anotherchrisberry This is a kick-the-tires PR.  Please pull down to and test to make sure everything works.

### CODE REVIEW

**Comment by duftler** [comment]
@zanthrash Ok to get to this tomorrow?

**Comment by zanthrash** [comment]
@duftler Yeah, when ever you have time.

**Comment by anotherchrisberry** [comment]
@lwander Can you take this for a spin, too? I don't think it'll have any adverse effects, just want to make sure.

**Comment by lwander** [comment]
@anotherchrisberry, @zanthrash, works fine for kubernetes!

**Comment by anotherchrisberry** [comment]
needs a rebase but let's ship it

**Pull request merged**
