### PR TITLE
chore(core/amazon/docker/google): update configs

### PR DESCRIPTION
**Pull request by icfantv**
* update package configs to add task for cleaning and change
`prepublish` to `prepare` to fix deprecation warning when publishing.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by danielpeach** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
I like the idea of running the `clean` command before publishing.

**Comment by christopherthielen** [comment]
+1 for cleaning

**Comment by icfantv** [comment]
updated and rebased.

**Pull request merged**
