### PR TITLE
introduce stageConfigField directive

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Simple directive to render labels and fields consistently across stages.

This would have been much easier to have done 11 months ago before there were more than 30 stages with all this boilerplate code, but it's easier now than it will be in another 11 months, I suppose.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@duftler feel like reviewing this?

**Comment by anotherchrisberry** [comment]
or @zanthrash

**Comment by duftler** [comment]
Sure. Looking now.

**Comment by duftler** [comment]
I pulled the branch and walked through configuration of each affected pipeline stage. Each seemed to render properly.
LGTM.

**Pull request merged**
