### PR TITLE
(appengine) only show start/stop stages for appengine applications

### PR DESCRIPTION
**Pull request by danielpeach**
@tomaslin please review.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by tomaslin** [comment]
es good

**Comment by cfieber** [comment]
@danielpeach @duftler random question - how is start / stop in appengine different than enable / disable (both sort of seem about the service taking traffic?)

**Comment by danielpeach** [comment]
@cfieber a stop operation on an App Engine server group forces it to scale down to zero instances; a start operation lets a server group scale according to its scaling policy.

We had some debate about whether to force fit start and stop into existing Spinnaker operations (resize seemed closest), but couldn't find a reasonable mapping.

**Comment by cfieber** [comment]
thanks!

**Pull request merged**
