### PR TITLE
Remove Netflix specifc defaultSecurityGroups

### PR DESCRIPTION
**Pull request by moondev**
Prevents errors when these security groups do not exist.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
I think this makes sense. 

I assumed folks were always customizing this file, but I guess not. 

Do you set environment variables for `gateHost` and `authEndpoint` when you run Deck locally?

**Comment by anotherchrisberry** [comment]
just needs a rebase

**Comment by anotherchrisberry** [comment]
hmm, looks like it's still out of date - can you rebase one more time?

**Comment by moondev** [comment]
I do use the env vars for gate and rosco when I build deck, works great!

**Pull request merged**
