### PR TITLE
Rename rebakeControlEnabled to roscoMode, as it now guards more than …

### PR DESCRIPTION
**Pull request by duftler**
…just the single Rebake control.

Add support to Bake Stage for optional Template File Name field (it is only rendered if roscoMode is enabled).

### CODE REVIEW

**Comment by duftler** [comment]
https://github.com/spinnaker/orca/pull/721 should be merged first.

**Comment by duftler** [comment]
Relates to https://github.com/spinnaker/spinnaker/issues/692.

**Comment by anotherchrisberry** [comment]
You probably want a separate code change for this line:
https://github.com/spinnaker/spinnaker/blob/master/config/settings.js#L89

**Comment by duftler** [comment]
Thanks, got that here: https://github.com/spinnaker/spinnaker/pull/708

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
