### PR TITLE
fix(RunJobStage): Make RunJobStage restartable

### PR DESCRIPTION
**Pull request by AbdulRahmanAlHamali**
This is supposed to fix this issue:
https://github.com/spinnaker/spinnaker/issues/5461

Is there a reason why the RunJobStage doesn't have the `restartable` property on it?

### CODE REVIEW

**Comment by AbdulRahmanAlHamali** [comment]
I confirmed that this is just a UI issue, because I was able to restart it using the API.

Looking at Deck's code, I find a lot of things that should probably be read from the API instead of hard-coded here. There seems to be multiple sources of truth

**Comment by maggieneterval** [comment]
Thanks for the PR, @AbdulRahmanAlHamali! Looping in @ethanfrogers in case there is some reason I'm not recalling that at least the Kubernetes Run Job stage should not be restarted.

**Comment by christopherthielen** [comment]
👍  from me

**Comment by AbdulRahmanAlHamali** [comment]
I get the impression that @ethanfrogers is on vacation. So I don't know if we'll be able to make the release. 

But I've called `restart` using the API a few times, and it worked with no issues. It feels that we just forgot to add the button in the UI

**Pull request merged**
