### PR TITLE
Aws block device user interface

### PR DESCRIPTION
**Pull request by skorten**
Add block device configuration to amazon servergroup advanced settings.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
If I'm reading this correctly, there will always be an empty array of `blockDevices` on the command, which means [this block in Clouddriver](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/BasicAmazonDeployHandler.groovy#L189-L191) never gets called.

That seems like a breaking change - at least on the Netflix side of things. Or I'm reading some part of this incorrectly.

**Comment by skorten** [comment]
@bsawyer @pansonm Please see @anotherchrisberry comment above.

**Comment by pansonm** [comment]
Agree with @anotherchrisberry. Ben and I discussed the empty `blockDevices` array but did not see the problem downstream. It will need to be removed. Thanks Chris!

**Comment by bsawyer** [comment]
Added the deletion of blockDevices property on cluster model to meet the conditional requirements spotted by @anotherchrisberry.

**Comment by anotherchrisberry** [comment]
This change will present the following in the Advanced settings view of server group configuration:
screen shot 2016-05-05 at 7 52 15 am

Two UX suggestions: 
 1. If "EBS Volumes" is empty or zero, we should hide the other three fields (Volume Size, Volume Type, Delete Volumes on Termination). And, since the first two fields are number fields with a relatively small max value, we should explicitly set the width of the inputs to 100px.
 2. There are three fields between "AMI Block Device Mappings" field and this field. If "AMI Block Device Mappings" is checked, it's going to override any of the block device configuration. We should probably move that field so it's immediately preceding the block device config fields here, and hide those fields if "AMI Block Device Mappings" is checked.

The resulting device names will be `/dev/sda`, `/dev/sdb`, `/dev/sdc`, etc., and will all have the same type and capacity. @ajordens or @cfieber any concerns about this approach? I don't have much familiarity with how teams are using and customizing block devices.

Will mappings carry over when doing a server group clone operation? I don't see `blockDevices` being set on the command anywhere outside this directive, so it _seems_ like the answer is "no". It's probably less an issue when creating a server group configuration in a pipeline, but when cloning an existing ASG to create a new one, that behavior might be surprising.

**Comment by pansonm** [comment]
Agree with the UX suggestions from @anotherchrisberry and also the inclusion of `blockDevices` in clone server group operation. The clone operation works as intended. However, the block device config values aren't displayed in the UI which is confusing. We're looking into fixing this. The same issue exists for the "Prefer AMI Block Device Mappings" checkbox -- it isn't checked in the clone UI but the cluster is produced as expected, honoring the AMI mappings.

We decided to go with a simple interface for specifying all block devices rather than specifying parameters individually for each device (e.g. add/remove device). This was based on recommendations from some of our DevOps engineers. @ajordens agreed with this approach on the weekly call today. We can certainly revisit if there is interest in more granularity (and complexity) for block device specification.

**Comment by pansonm** [comment]
@anotherchrisberry, regarding the clone ServerGroup feature and the UI not being populated with block device fields. This is tricky and would like to get your input on a solution. Population of the clone ServerGroup form is based on the existing ServerGroup object which is fetched after you invoke clone. This contains no information about how the block devices were specified in the pipeline ServerGroup (e.g. Netflix default settings, Prefer AMI Device Block Mappings checkbox or the new fields we've defined). All you get is the raw block device objects. Without tying back to a pipeline (if one exists), it doesn't look like it's possible to determine how to populate the UI. Since the clone operation is based on the JSON, it does properly clone the block devices. Any thoughts here?

**Comment by anotherchrisberry** [comment]
@pansonm Sorry, I'm OOO this week (and most of next week), so am a little late responding.

I _think_ we can determine if default settings are being used by looking at https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/BlockDeviceConfig.groovy - we could either a) pump the default configs from this class out via an endpoint in Clouddriver (and Gate) or b) copy the logic in here to determine whether an existing launch config is using the defaults. Neither option is great: a) means adding a provider-specific endpoint, something we try to avoid; b) means duplicating logic in Clouddriver and Deck. My vote is b), even though we'd need to keep it in sync if changes are ever made in Clouddriver; other (e.g. @ajordens ) may disagree.

Once we have those defaults available to the UI, would we be able to look at the server group's launch config to see what the `blockDeviceMapping`s are and how to set the "Prefer AMI Device Block Mappings"? Or are there other pieces of puzzle to consider?

**Comment by anotherchrisberry** [comment]
After a long and contentious conversation, here's what we'd like to see:

When Clouddriver performs a deployment, we should tag the ASG with a tag to capture the user decision around device mappings. Let's create a tag with a key of "spinnaker:deploymentMetadata" and the following structure:
```json
{"deviceMapping":"ami"}
```
where "ami" is one of: 
 * "ami": user selected "Prefer AMI Block Device Mappings"
 * "default": user did not select anything, so Clouddriver chose the default block device mappings
 * "custom": user specified block device mappings via these new fields

We are thinking we'll add at least one more field to this tag: "executionId", which will let us track how this ASG was created, but that'll be down the road.

The main reason for using a tag: trying to determine how the device block mappings were configured after the fact is going to be a huge pain. We need to look at the AMI attributes, we need to know what those defaults are, and we need to know what those values were _when the ASG was created_, since the defaults may have changed.

If we just start tagging ASGs as we create them, we can assume "default" if there's no tag.

Does that sound reasonable/make sense?

**Comment by pansonm** [comment]
Storing spinnaker/orchestration metadata in the ASG is a little suspect vs using a spinnaker data source. Assuming this is where the contention came from. But it is a much simpler solution than changing data models and access patterns between clouddriver and deck and follows the established pattern of inferring metadata from infrastructure naming/conventions. Makes sense to me @anotherchrisberry. @bsawyer I'll take a look at the tagging during ASG creation and we can take from there.

**Comment by pravka** [comment]
@pansonm did you have a change to look at tagging the ASG during creation?

**Comment by pansonm** [comment]
@pravka We're going to be looking at this next week. There is an outstanding question about whether we have enough information at time of ASG creation to create the tag.

**Comment by katrielt** [comment]
A few comments and questions:
a. According to the suggestion, a use would be able to add a number of EBS volumes, starting with sda. sda1 is by default a the root partition, so I think there will be a conflict there.
b. I don't see any reference to changing the size of the root device. I believe allowing to change the root device size will be useful.
c. There's no reference to ephemeral devices. I think that if the instance type allows it, they should be included in the new Block Device Mapping.

I guess what I'm getting at, is I think it would be much more useful to implement a something more similar to AWS's "Create Image" from a running instance.

**Comment by pansonm** [comment]
@katrielt Thanks for the comments. Will respond to each:

a. The block device names start from /dev/sdb and then progress to /dev/sdc, /dev/sdd, etc. This should not create conflicts.
b. Great point and we are planning to implement override of root device size next. This will be a separate field in the UI.
c. We're open to implementing instance volumes. This PR is addressing EBS volumes only. As you point out, ephemeral devices can be tricky because of the dependence on instance type to determine valid device number and size: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html

Regarding create image from running instance: You could certainly create an image from a running instance and use Spinnaker to deploy that image. Spinnaker does not expose this functionality and in general starts with a Base AMI rather than being a tool to create new Base AMI's. This PR addresses overriding Base AMI EBS devices during pipeline execution.

There are many possibilities for device configuration. Our approach has been to offer a reasonable amount of functionality without creating an overly complex UI with a lot of instance specific logic.

**Comment by JinpaLhawang** [comment]
@anotherchrisberry Nicholas Eden-Walker here, @pansonm mentioned me earlier. We've implemented the change as you suggested, in clouddriver, specifying "default", "ami" or "custom" as appropriate. During review, @pansonm pointed out that "custom" was used for 2 different cases: 1) when the user directly edits the JSON (a sort of freeform custom) and 2) when the user enters the number of EBS volumes, size and type and has the block devices generated (a sort of generated custom).

Some options:
1) We leave the clouddriver code changes as is accepting that "custom" could be either situation.
2) We actually move the tagging from clouddriver to deck. It would be a bit tricky in clouddriver to ascertain which custom form was used to create the Block Devices to properly tag, but deck actually knows everything to make the tag designation, including whether the user has chosen to Prefer AMI or use the default Netflix implementation.
3) We keep tagging of "ami" and "default" in clouddriver and do "custom" tagging in deck, which sounds... brittle.

**Comment by katrielt** [comment]
@pansom thanks for the info. Some more comments:
a. In the original mockup and explanation by @anotherchrisberry , he mentioned sda. Just wanted to make sure that's not the case, so thanks for clearing up.
b. good to know. any timelines?
c. I wasn't actually suggesting "Create Image" will be implemented by Spinnaker, rather that a similar UI will be used for custom Block Device Mapping UI. There's already been some work with regards to filtering fields based on instance type, so I don't think that should be too hard to do.

Would you consider always adding 4 ephemeral devices to a custom BDM? This shouldn't cause any problems when an instance doesn't have ephemeral storage, at the same time, guaranteeing that an instance that does, sees all ephemeral storage.

**Comment by anotherchrisberry** [comment]
@JinpaLhawang Sorry, I've been on vacation (again) and am just catching up here. Sounds like you're suggesting we set the `deviceMapping` key in the "spinnaker:deploymentMetadata" tag via Deck, right? That makes sense to me.

**Comment by anotherchrisberry** [comment]
Closing - this is over a year old. We've got something in the works to accommodate block device mappings.

**Pull request closed without merging**
