### PR TITLE
feat(core/managed): support for marking a version 'bad', add illustrations

### PR DESCRIPTION
**Pull request by erikmunson**
~~**Depends on https://github.com/spinnaker/deck/pull/8336**~~

We previously added a workflow for [pinning an artifact version to an environment](https://github.com/spinnaker/deck/pull/8238), which is helpful for things like rollbacks/rollforwards and temporarily halting deployments to an environment. The next step in supporting manual override workflows is _marking a version as 'bad'_.

This is useful for times where you don't care about which version specifically runs in an environment, but you want to make sure a broken version is never chosen. Today we'll already mark a version as bad automatically if we try to deploy it and it fails multiple times, but now you can choose to do the same thing manually.

A _ton_ of this code is copy-pasta from the pinning flow, which is generally a good thing. I'm not at all convinced these flows will remain the same under the hood and I'd like to retain the flexibility to do large refactors on one or both. Alongside the new flow, I've also updated the pin + unpin flows to use the new illustrations @gcomstock put together, along with tweaking the layouts + explanatory copy so they match our updated mockups more closely.

Screenshots:

<details>
<summary>New action button on versions</summary>

Screen Shot 2020-06-08 at 4 35 50 PM

</details>

<details>
<summary>Modal flow for marking as bad</summary>

**Normal:**
Screen Shot 2020-06-08 at 1 33 35 PM

**When an environment is already marked bad:**
Screen Shot 2020-06-08 at 1 33 45 PM

**When an environment is already pinned:**
Screen Shot 2020-06-08 at 1 47 52 PM

</details>

<details>
<summary>Version / environment card after pinning</summary>

Screen Shot 2020-06-08 at 3 47 38 PM

</details>

<details>
<summary>New pin illustration + layout</summary>

**Normal:**
Screen Shot 2020-06-08 at 1 32 25 PM

**When an environment is already marked bad:**
Screen Shot 2020-06-08 at 1 33 11 PM

</details>

<details>
<summary>New unpin illustration + layout</summary>

Screen Shot 2020-06-08 at 1 34 28 PM

</details>

cc @gcomstock

### CODE REVIEW

**Comment by luispollo** [comment]
Looks gorgeous!

**Comment by gcomstock** [comment]
Screen Shot 2020-06-08 at 5 03 49 PM

Beautiful! Minor nit on "Check out our documentation" and the previous sentence: I think there should either be an extra line of whitespace, or there shouldn't be a full return.

**Comment by erikmunson** [comment]
> I think there should either be an extra line of whitespace, or there shouldn't be a full return.

@gcomstock argh yeah you caught me. I 'settled' on this (a.k.a. I gave up) because I felt like both were awkward in context. let me just show you what each looks like and we can discuss:

Screen Shot 2020-06-08 at 5 11 32 PM
Screen Shot 2020-06-08 at 5 11 52 PM
Screen Shot 2020-06-08 at 5 09 52 PM
Screen Shot 2020-06-08 at 5 11 05 PM

Can you just tell me which to use?? I've already been looking at these layouts for too long to feel like I'm evaluating them coherently 😆😭😎

**Comment by gcomstock** [comment]
😆  Let's go with extra line of whitespace!

**Comment by erikmunson** [comment]
Excellent, sold, I'm doing it ❤️

**Comment by erikmunson** [comment]
> Does it make sense to allow marking a version bad across all environments through a single action in the modal?

YES thanks for bringing this up — greg and I discussed it verbally but I neglected to cover that idea in the PR description. Completely agree that in many cases marking bad everywhere is what folks will truly want to do. I'm doing this now because it's an easy copy-paste job and there's a workaround (it's just tedious), but if @gcomstock has ideas for a quick way to be able to select "all" the available options that doesn't take much UI engineering work i bet the API side could also be modified to take a list of environments (right now it only accepts one).

**Pull request merged**
