### PR TITLE
(core) refactored cluster, lb, and security group dependent filters

### PR DESCRIPTION
**Pull request by danielpeach**
@anotherchrisberry please review (I think I've got it right this time).

### CODE REVIEW

**Comment by duftler** [comment]
I played with this a bit and it seems to work as expected.
Btw, any reason not to move the 'Provider' section to the top? Now that the cascading logic affects pretty much everything, it feels like it's in the wrong slot.

**Comment by anotherchrisberry** [comment]
Works well for me. I think Matt's question is a good one - makes sense to move Provider to the top while you're in there changing the other things.

**Comment by danielpeach** [comment]
Updated with Provider as the top-level header.

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
