### PR TITLE
feat(core): allow application pipelines outside executions view

### PR DESCRIPTION
**Pull request by anotherchrisberry**
In our custom version of Deck, we use pipelines to deal with property configuration rollouts. Some teams want to use custom templates, basically, to handle their property rollouts, so we are thinking we can use the pipeline configuration view to let them do this - or at least use Front50 as a mechanism to store the pipeline configurations.

Does this seem like a reasonable approach? Not in love with `dataSource` as the field name but not thinking of anything better right now...

@jrsquared @christopherthielen @danielpeach @erikmunson @sbwsg any feedback or opinions welcome here.

### CODE REVIEW

**Comment by danielpeach** [comment]
LGTM

**Comment by sbwsg** [comment]
:+1:

**Comment by jrsquared** [comment]
lgtm

**Comment by anotherchrisberry** [comment]
I don't like this, sorry for wasting everyone's time.

**Comment by jrsquared** [comment]
typical

**Pull request closed without merging**
