### PR TITLE
SPIN-1418: Add Cluster selector to pipeline stages that require selecting a cluster.

### PR DESCRIPTION
**Pull request by zanthrash**
Also fixing a bug that surfaced in the deployed quick patch stage where a saved cluster name was getting marked undefined upon stage load.
This fixes the QIP stage and all the other stages that use the cluster selector.

The cluster filter was also extracted into a factory function that can be used across all stages.

@anotherchrisberry please review.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
Found one more place to add the cluster picker...
https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/pipeline/config/preconditions/types/clusterSize/additionalFields.html

**Comment by anotherchrisberry** [comment]
If you want to rebase and merge to master (and deal with the check preconditions modal later), I'm good with that.

**Comment by zanthrash** [comment]
@anotherchrisberry I'll merge these changes and just cut a new PR for the preconditions.

**Pull request merged**
