### PR TITLE
Adds 1-click access to the actual error at the last level pipeline

### PR DESCRIPTION
**Pull request by sseale**
feat(execution/ExecutionMarkerInformationPopover) Adds 1-click access to the actual error at the last level pipeline

- New feature can be enabled/disabled via executionMarkerInformationPopover in the settings.js spinnakerSettings:feature section
- ExecutionMarker.tsx now loads the new component and for a stage with status 'terminal', type 'pipeline' and will add an font-awesome information circle icon to the stage
- When information icon is clicked popover will load and traverse through the execution => terminal stage(pipeline) until the last instance is found then report that actual error stage and execution allowing for quick access and viewing
- popover is not using jquery or bootstrap but does use the react-bootstrap css classes
- ExecutionMarkerInformationPopover component adds/removes listeners for the window.resize and '.all-execution-groups' scroll events to allow for updating it's position and 'nubbin' position, scrolling the clicked stage as it hit the stop container will close
- ExecutionMarkerInformationPopoverState caches and validates api calls returning cached versions for quicker access since there can be many calls made to the same execution/pipelineConfigs etc
- Lists the execution history in reverse order as clickable rows
- Has secondary area for showing history again in reverse order using the spinnaker PipelineGraph component

9aa5a480-a194-11ea-8109-d14f293378f7
9e392b80-a194-11ea-8b3e-c41cfe1afb22

### CODE REVIEW

**Comment by RodEsp** [comment]
Heya @maggieneterval this is the PR we talked about during the SIG UI meeting yesterday. Can't assign reviewers so just tagging you here :)

We'll be fixing up the automated checks shortly.

**Comment by maggieneterval** [comment]
@RodEsp excited to review this, will add myself as a reviewer now! Let me know when the CI passes and I will take a look!

**Comment by RodEsp** [comment]
@maggieneterval ok should be good to go!

Btw, we opened this against `release-1.19.x` because this is the version we are currently using at SF, please let us know if you have a different branch you'd like us to PR against.

Also we'd obviously like to see it in future releases as well.
Is there anything you would like us to do to merge these changes forward or is this already handled automatically?

**Comment by maggieneterval** [comment]
@RodEsp Thanks for pointing that out! Since this is a feature, please make this PR against the master branch. Only fixes can be merged to release branches.

**Comment by RodEsp** [comment]
Ok @maggieneterval, I opened up #8325 to replace this PR.
Feel free to close this one whenever you'd like.

**Comment by maggieneterval** [comment]
Thanks, closing this one now!

**Pull request closed without merging**
