### PR TITLE
chore(ci): GHA - container image and apt package build & push - backport #9823

### PR DESCRIPTION
**Pull request by kskewes-sf**
manually backport from `master` branch #9823 because mergify backport #9829   resulted in git conflicts..

### CODE REVIEW

**Comment by kskewes-sf** [comment]
Blocked on #9827 and #9828.

After in will redo this without pulling those in and force push to tidy this up.

**Comment by kskewes-sf** [comment]
eslint plugin build failing (before doing `yarn modules` first): https://github.com/spinnaker/deck/runs/5652513730?check_suite_focus=true

eslint rules failing: https://github.com/spinnaker/deck/runs/5652585505?check_suite_focus=true

**Comment by kskewes-sf** [comment]
There are a bunch of `eslint` related PR's that have merged into master for 1.28.x that aren't in 1.27.x.

We can either:
1. disable eslint for 1.27.x
2. backport eslint fixes to 1.27.x

**Comment by kskewes-sf** [comment]
Prettier linting also [failed](https://github.com/spinnaker/deck/runs/5652942623?check_suite_focus=true).
```
$ prettier --check '{app,packages}/**/*.{js,jsx,ts,tsx,html,css,less}'
Checking formatting...
[warn] packages/amazon/src/loadBalancer/configure/network/TargetGroups.tsx
<snip>
[warn] packages/titus/src/serverGroup/details/TitusCapacityDetailsSection.tsx
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
```

**Review by dbyron-sf — APPROVED** [review]

**Pull request merged**
