### PR TITLE
feat(core): allow markdown in stage-level comments

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Addresses the comment in https://github.com/spinnaker/spinnaker/issues/2005#issuecomment-372429960

### CODE REVIEW

**Comment by erikmunson** [comment]
👍

**Comment by t0mpson** [comment]
@anotherchrisberry Thanks so much! I'll test once a release is cut.

**Comment by anotherchrisberry** [comment]
@t0mpson - give it a shot when you have a minute: https://github.com/spinnaker/deck/releases/tag/v2.1182.0

**Comment by t0mpson** [comment]
@anotherchrisberry 

Works like a charm! Thanks a bunch!

Now we can surface lots of useful info both in the popup & comments in each stage. 

For eg, I'm using this to: 

- Show who triggered the pipeline (or approved a manual judgement).
- Expose versioning info
- some more info
- memes 

All thanks to your help! 

screen shot 2018-03-13 at 9 09 59 pm

**Comment by anotherchrisberry** [comment]
@t0mpson Awesome, glad to hear it! You should write a blog post about it!

**Pull request merged**
