### PR TITLE
(core): some at-types stuff

### PR DESCRIPTION
**Pull request by icfantv**
* update some old versions
* pin lodash due to compiler issues on latest

### CODE REVIEW

**Comment by icfantv** [comment]
@anotherchrisberry @zanthrash @danielpeach PTAL

mainly to pin lodash's @types as the latest patch release has issues the compiler is complaining about.

**Comment by anotherchrisberry** [comment]
probably worth pinning these more consistently with the actual dependencies, e.g. we have `angular` at `~1.5.8` but pinning `@types/angular` to `1.5.8`

**Comment by anotherchrisberry** [comment]
Otherwise, LGTM

**Comment by icfantv** [comment]
yea, good call.  will update.

**Comment by icfantv** [comment]
Pinned versions for now.  Looks like if we update to angular 1.6 we can get the versions more in line with each other.  I can't drop core angular to 1.5.8 to match angular-mocks or we'll get compiler errors.  We should look at upgrading to angular 1.6 at some point.

**Pull request merged**
