### PR TITLE
(core): remove uuid service from the angular realm

### PR DESCRIPTION
**Pull request by icfantv**

### CODE REVIEW

**Comment by icfantv** [comment]
@anotherchrisberry @zanthrash PTAL

**Comment by anotherchrisberry** [comment]
LGTM, although I'm not sure about keeping it named "UUIDService" - "service" makes me think it's an Angular component. Maybe "UUIDGenerator"?

**Comment by icfantv** [comment]
Sure.  I'm ok w/ that.  Or maybe `UUIDNotAnAngularService`?

**Comment by icfantv** [comment]
_this house, is clean_

renamed.

**Pull request merged**
