### PR TITLE
Corrected deck Dockerfile

### PR DESCRIPTION
**Pull request by aarondobbing**
Copied apache configuration files to allow start up - Have tested and is operating as expected. Image can be tested from docker.io/aarondobbing/deck:latest

### CODE REVIEW

**Comment by aarondobbing** [comment]
@ttomsu - Included configuration files required by apache - Sorry for missing this on the last PR, i was running out of the door and saw the container start up fine.

Have tested properly in cluster, and apache is serving as expected.

**Comment by aarondobbing** [comment]
@dforrest88 - FYI, this is working and tested on my cluster - If you didnt fix or build yourself yesterday :)

**Comment by ttomsu** [comment]
Thanks for fixing this @aarondobbing !

**Comment by dforrest88** [comment]
Hmm.. I'm not entirely sure of the whole build/release process for this component, but I pulled the latest master tag a few minutes ago and although the apache start script is there, I'm still hitting errors with some other files.

```
dforrest-ltm:trace-bot dforrest$ docker run quay.io/spinnaker/deck:master
cp: cannot stat ‘docker/spinnaker.conf.gen’: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
mv: cannot stat ‘spinnaker.conf’: No such file or directory
ERROR: Site spinnaker does not exist!
cp: cannot stat ‘docker/ports.conf.gen’: No such file or directory
sed: can't read ports.conf: No such file or directory
sed: can't read ports.conf: No such file or directory
mv: cannot stat ‘ports.conf’: No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
```

**Comment by aarondobbing** [comment]
If you check the image as per original PR - docker.io/aarondobbing/deck:latest it will be working - Working and tested in my installation now - Im unsure if there are trailing references to the directory elsewhere after it being moved into /opt

Feel free to build deck from my fork for a working copy or use the image i have on my latest tag in dockerhub.

**Comment by aarondobbing** [comment]
@ttomsu in order to move into /opt you will need to change the references in run-apache2.sh for the sed replacements (e.g. https://github.com/spinnaker/deck/blob/master/docker/run-apache2.sh#L27)

**Pull request merged**
