### PR TITLE
Improvements to AMI and instance type validations, custom instance type selector

### PR DESCRIPTION
**Pull request by pdk27**
## Status: 
draft / early review

## Pre-req PRs:
https://github.com/spinnaker/clouddriver/pull/5609

## Changes:
- Adding architecture to AWS image type
- Adding instance type information to AWS instance type 
- Adding `AmazonInstanceType` to `AmazonServerGroupCommand` to make instance type info available
- Improved validations / filtering of incompatible instance types:
   - new validation between AMI architecture and instance types' architecture
   - removed hard-coded instance family mapping for virtualization type validation, replaced with instance type info usage
   - added clarity around `vpcOnly` or `ec2Classic` validation
   
### UI changes:
- Displaying instance type info in Custom instance type selector in 2 places:
   - As a tooltip for already selected instance types
   - Enhanced drop down for list of available instance types
- Adding filtering capability to the drop down in custom instance type selector. Filters implemented:
    - instance family / size / type e.g. c3/ large/ c3.large
    - min vcpu e.g. 16vcpu
   * min memory e.g 32gib
   * instance storage type e.g. ssd, hdd
   * spot support
   - ebs support
   * gpu support
   * current generation v/s old generation like 'currentGen' / 'oldGen'

## Screenshots & Demo:

* Demo

https://user-images.githubusercontent.com/3614196/147281154-7e7fa515-37cc-4f46-b7b5-42875f001eac.mov

* Custom instance type select before changes
  

* Help tooltip & drop down improvement
     

*  Filter Example & info for selected type

* Filter Example
 

* Filter Example

### CODE REVIEW

**Review by caseyhebebrand — APPROVED** [review]

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by mattgogerly** [comment]
@pdk27 is this ready to go?

**Comment by pdk27** [comment]
> @pdk27 is this ready to go?

@mattgogerly I have a pre-requisite PR that needs to be merged in for these changes to work - https://github.com/spinnaker/clouddriver/pull/5609

**Comment by dbyron-sf** [comment]
@mergifyio update

**Review by mattgogerly — APPROVED** [review]

**Pull request merged**
