### PR TITLE
Stages are only restartable if their pipeline is not RUNNING

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by ajordens** [comment]
FYI @anotherchrisberry (I see you online?)

Corrects an issue where currently running pipelines can be restarted (_resulting in multiple copies of the pipeline running concurrently_).

Poses a particular problem if you have stages that are conditional on previous stages (SPIN-2020).

**Comment by anotherchrisberry** [comment]
LGTM

**Comment by anotherchrisberry** [comment]
Need to fix ze tests

**Comment by ajordens** [comment]
Tests be fixed

**Pull request merged**
