### PR TITLE
Adding support for internet-elb v2.

### PR DESCRIPTION
**Pull request by ajaijoy**
1. The checkbox for isInternal appears only for vpc.
2. Updated loadBalancer.transformer.js to have isInternal flag.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Looks good, but it's out of date. Can you do this from the command line?
 1. `git pull --rebase upstream master`
 2. `git push -f`

**Comment by ajaijoy** [comment]
ok just did the above 2 commands. Will create a new cloudriver pull request now

**Comment by ajaijoy** [comment]
@anotherchrisberry  Chris, do you anticipate any further changes ? If not, any timelines for merge ? This is my first commit hence asking.

**Comment by anotherchrisberry** [comment]
@ajaijoy I don't think you'll need to change anything in the code itself; however, I can't merge it until this PR is merged: https://github.com/spinnaker/clouddriver/pull/323. Once that happens, you'll probably need to rebase this once more - let's keep an eye on the clouddriver PR and try to get this merged right around the same time.

**Comment by ajaijoy** [comment]
@anotherchrisberry  Hi Chris, i just rebased the deck change and Clay has merged spinnaker/clouddriver#323

**Comment by anotherchrisberry** [comment]
Awesome, thanks, @ajaijoy - I'll merge this as soon as the CI build completes.

**Pull request merged**
