### PR TITLE
(core) add ng2 libs and deps

### PR DESCRIPTION
**Pull request by icfantv**
* upgrade app to latest RXJS per ng2 requirements

DO NOT MERGE, WIP!!!

### CODE REVIEW

**Comment by icfantv** [comment]
Crap.  WebStorm's auto-formatter added a ton of whitespace noise.  I'll need to see if this can be easily backed out....

**Comment by icfantv** [comment]
Oh SWEETNESS!  add `?w=1` to the URL to ignore whitespace.

**Comment by anotherchrisberry** [comment]
nice, LGTM

**Comment by anotherchrisberry** [comment]
Tested and everything seems to work without any issue.

Moving forward, probably a good idea to not auto-format code, especially when touching this many files, as it makes it hard to pick out what the actual code changes are.

**Comment by anotherchrisberry** [comment]
Merge away after it's rebased.

**Comment by zanthrash** [comment]
👍

**Comment by icfantv** [comment]
@anotherchrisberry totally agree.  apparently webstorm does an entire doc reformat on autocomplete.  need to shut this off.

**Comment by gbougeard** [comment]
maybe use http://editorconfig.org/ ? it's handled by jetbrains tools

**Pull request merged**
