### PR TITLE
feat(helm/bake): Add additional input fields where we can fill in details of the APIs versions

### PR DESCRIPTION
**Pull request by ciurescuraul**
It would be incredibly helpful if SpEL expression parameters could be used for the API and Kubernetes versions in the Bake Manifest stage when baking Helm charts. This feature would allow users to deploy different versions of artifacts based on the target cluster API and K8s versions, significantly improving their workflow.

- These input fields will not be pre-populated with versions of the target cluster available in the environment

- They will become part of the bake result when API_VERSIONS_ENABLED flag is enabled

- ApiVersions should be a subset of the API versions supported by the Kubernetes version specified in KubeVersion. In other words, the Kubernetes cluster version (Capabilities.KubeVersion) determines the range of API versions that are available in the cluster (Capabilities.APIVersions).

- Helm options configuration

- Evaluate variables stage

### CODE REVIEW

**Review by kkotula — APPROVED** [review]
LGTM

**Comment by kkotula** [comment]
PRs in other services for reference:
[Orca](https://github.com/spinnaker/orca/pull/4546)
[Rosco](https://github.com/spinnaker/rosco/pull/1020)

**Review by jasonmcintosh — APPROVED** [review]

**Review by ovidiupopa07 — APPROVED** [review]

**Comment by ovidiupopa07** [comment]
https://github.com/Mergifyio backport release-1.28.x release-1.30.x release-1.31.x release-1.32.x

**Comment by ovidiupopa07** [comment]
Since this new functionality is hidden behind a feature flag it is ok to backport

**Pull request merged**
