### PR TITLE
rewrite application load/refresh handling

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Who doesn't like a 3k line pull request?

I'm not pretending this is reviewable in any meaningful way, so I'll provide a summary of the changes, then ask @duftler , @lwander , @gregturn , @JargoonPard or someone from Azure to pull this down, kick the tires with the browser console open to see if any exceptions are being thrown.

So...

## Summary of the changes
_Load everything as fast as possible and render every view as fast as possible._ An application is made up of (basically) six data components:
 * server groups (aka clusters)
 * load balancers
 * security groups
 * pipeline executions
 * pipeline configurations
 * tasks
In its current state, the application must load the first four items before it will render anything on the screen. This is due to some decisions made long ago, where we needed to merge a bunch of separate calls to get our data in a presentable form. We've since smoothed over a lot of those problems by adjusting the responses we get from the backend. But we never fully refactored the application load: we still get those four components, then render the page. If the user is on the executions view, and those four components are still loading, the user won't see the executions, even if they are available. The same thing applies to the tasks view.

This PR breaks those components into separate buckets, with `rx.Subject`s for each one that consumers can subscribe to. I've also broken out separate buckets for `runningTasks` and `runningExecutions`, since those calls are generally very light and very fast, and it's not worth the headache of trying to manage their state based on which page the user is on (right now, we always fetch running tasks, unless the user switches to the tasks view, at which point we refresh and get all tasks). 

Overall, the code is a little easier to follow, and should be easier to maintain and adapt. Next step would be to get a grip on RxJS and do that part right, and make this pluggable so that, for example, the serverGroups module would register a section that the application reader would use to manage data. We need something like this for our fast properties module, and other integrators may want something similar.

In reality, this probably doesn't have any impact on users that have fewer than 1000 instances or 500 pipeline executions in any given application. For them, the UI is probably snappy.
_However_, we have to handle cases where there are several thousand instances, and hundreds of pipeline executions, and we need to get those pixels on the screen faster than we are now. This should help quite a bit.

### CODE REVIEW

**Comment by lwander** [comment]
Wow, thanks for doing all the providers!

**Comment by JargoonPard** [comment]
I'll check it out now.

**Comment by anotherchrisberry** [comment]
Thanks, @JargoonPard !

**Comment by lwander** [comment]
Works for GCE & Kubernetes as far as I can tell. @anotherchrisberry

**Comment by anotherchrisberry** [comment]
Going to merge this - if anyone runs into trouble, ping me and I'll get it fixed asap

**Pull request merged**
