### PR TITLE
Support locked (aka not editable via UI) pipelines

### PR DESCRIPTION
**Pull request by ajordens**
- New 'locked' pipeline config attribute
- All locked pipelines must be modified via the API

image

image

### CODE REVIEW

**Comment by ajordens** [comment]
PTAL @anotherchrisberry / @spinnaker/netflix-reviewers.

The `ng-if`'s all over the place seem suspect to me but not sure there's a nicer way of doing that.

**Comment by ajordens** [comment]
Open to feedback on whether we like `pipeline.locked` ... I suppose we could always migrate configurations if we found that a single boolean attribute isn't sufficient.

**Comment by ajordens** [comment]
FYI @spinnaker/google-reviewers -- This is a quick attempt to deliver on a request by an internal group for "managed" pipelines. In this context a managed pipeline is one that is created via an API and not intended to be modified by an end-user via the UI.

**Comment by anotherchrisberry** [comment]
Nice, LGTM

**Comment by duftler** [comment]
Nice.

**Pull request merged**
