### PR TITLE
Dynamically determine whether to show Subnet column in Deploy Stage edit view.

### PR DESCRIPTION
**Pull request by duftler**
Replace double-quotes with single-quotes to placate linter.
Add GCE Deploy Stage template message.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
I wonder if we should make this a little more abstract and allow cloud providers to specify in their configuration that they support subnet functionality, then use that to determine if we show the subnet column in that table. I assume Azure will support it, but some (Titan, possibly CF) won't, so it would end up as clutter in the UI.

@spinnaker/microsoft @gregturn can you provide thoughts on support for the subnet concept on your respective platforms?

**Comment by gregturn** [comment]
CF has support for a default domain and other domains but I'm not aware of subnet configuration options.

**Comment by JargoonPard** [comment]
We are currently managing subnets behind the scenes using some default algorithms. We would like to expose more end user configuration going forward so this works well for Azure. Making it abstract for each provider totally makes sense.

**Comment by duftler** [comment]
Great idea.
Actually, would be even better if we can make the logic to determine the subnet description pluggable. For AWS it's `subnetType`. But in GCE it's `subnet` or in some cases `(Auto-select)` depending on the type of `network`, and I have no way to really this with the current setup. I'm sure Azure would also like to have control over how to render this field.
I've backed-out the GCE-specific changes from this PR and re-submitted just as a placeholder while we work through it.

**Comment by duftler** [comment]
Rebased.
@anotherchrisberry PTAL.

**Comment by anotherchrisberry** [comment]
Very nice!

**Pull request merged**
