### PR TITLE
Added run-apache2.sh in order to allow container to start.

### PR DESCRIPTION
**Pull request by aarondobbing**

### CODE REVIEW

**Comment by dforrest88** [comment]
Just hit this issue, thanks @aarondobbing for fixing.

**Comment by ttomsu** [comment]
Sorry about that. Can't test this now, but will merge.

**Comment by dforrest88** [comment]
@ttomsu and @aarondobbing, FYI, I started this up after the merge and this is what shows as it's starting. There may be a couple of other things to look at.

` 2017-02-08T20:11:10.205532077Z cp: cannot stat ‘docker/spinnaker.conf.gen’: No such file or directory
2017-02-08T20:11:10.205558980Z sed: can't read spinnaker.conf: No such file or directory
2017-02-08T20:11:10.208133395Z sed: can't read spinnaker.conf: No such file or directory
2017-02-08T20:11:10.209906388Z sed: can't read spinnaker.conf: No such file or directory
2017-02-08T20:11:10.214115108Z mv: cannot stat ‘spinnaker.conf’: No such file or directory
2017-02-08T20:11:10.285686378Z ERROR: Site spinnaker does not exist!
2017-02-08T20:11:10.287742404Z cp: cannot stat ‘docker/ports.conf.gen’: No such file or directory
2017-02-08T20:11:10.290058920Z sed: can't read ports.conf: No such file or directory
2017-02-08T20:11:10.291700956Z sed: can't read ports.conf: No such file or directory
2017-02-08T20:11:10.295544568Z mv: cannot stat ‘ports.conf’: No such file or directory
2017-02-08T20:11:10.319809259Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.2.76.114. Set the 'ServerName' directive globally to suppress this message `

**Comment by aarondobbing** [comment]
Will go take a look now.... Looks like there is a little more required that is removed in the deletion. I didn't have a chance to properly test as i was running out of the door at the office and saw it start up successfully on my cluster. Presumed it was just the one file missing that was overlooked in the deletion.

**Comment by aarondobbing** [comment]
@dforrest88 how are you running the docker image? I cant replicate on my k8s cluster.

**Comment by dforrest88** [comment]
This is my replicaset config.

`apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-deck-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-deck-v000
  template:
    metadata:
      labels:
        replication-controller: spin-deck-v000
        load-balancer-spin-deck: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/deck:master
          imagePullPolicy: Always
          name: deck
          env:
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "9000"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config`

**Comment by dforrest88** [comment]
This is my replica set config (out of the box)

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: spin-deck-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-deck-v000
  template:
    metadata:
      labels:
        replication-controller: spin-deck-v000
        load-balancer-spin-deck: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/deck:master
          imagePullPolicy: Always
          name: deck
          env:
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "9000"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
```

**Comment by dforrest88** [comment]
I can also reproduce locally:

`dforrest-ltm:kubernetes-tracebot dforrest$ docker run quay.io/spinnaker/deck:master
cp: cannot stat ‘docker/spinnaker.conf.gen’: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
sed: can't read spinnaker.conf: No such file or directory
mv: cannot stat ‘spinnaker.conf’: No such file or directory
ERROR: Site spinnaker does not exist!
cp: cannot stat ‘docker/ports.conf.gen’: No such file or directory
sed: can't read ports.conf: No such file or directory
sed: can't read ports.conf: No such file or directory
mv: cannot stat ‘ports.conf’: No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message`

**Comment by aarondobbing** [comment]
@dforrest88 im currently on a v slow upload with limited access - Could you build from my master fork and let me know if that solves it for you?

**Pull request merged**
