### PR TITLE
feat(provider/azure): Add redblack strategy for azure

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Background:
Add redblack strategy for azure provider.
There is another related PR (https://github.com/spinnaker/clouddriver/pull/3533) with same name in clouddriver for azure redblack strategy. Please also help to review.

### CODE REVIEW

**Comment by neil-yechenwei** [comment]
@sbwsg , @duftler , a kindly ping to review this PR. The purpose of this PR is to add redblack strategy for azure provider. Please help to review it.

**Comment by sbwsg** [comment]
As much as possible we'd like new components and features to be in React rather than Angular 1.x.

**Comment by sbwsg** [comment]
@neil-yechenwei code looks good to me. If you're able to convert the four new files over from angular to React that would be great. Feel free to ping me with any questions or, if it simply isn't possible, let me know and I'll merge this as-is.

**Comment by mybayern1974** [comment]
@sbwsg, is it ok to merge it now given one of our customers only use the Red/Black strategy so we'd like to unblock them asap. Meanwhile we will start the work of converting these newly added files to react from now on, and please expect our next PR to have it.

**Pull request merged**
