### PR TITLE
feat(provider/ecs): Added horizontal scaling section to deploy modal

### PR DESCRIPTION
**Pull request by BrunoCarrier**
feat(provider/ecs): Added horizontal scaling section to deploy modal

@anotherchrisberry @jrsquared @christopherthielen @dkirillov

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Seems to be a duplicate of https://github.com/spinnaker/deck/pull/4632

**Comment by BrunoCarrier** [comment]
@anotherchrisberry It is not a duplicate of #4632.  This is about vertical scaling (size of the container), whereas horizontal is about autoscaling policies / desired count:

image

**Comment by anotherchrisberry** [comment]
The code in this PR is identical to the code in 4632.

**Comment by BrunoCarrier** [comment]
Ah yes my bad, sorry.  Will correct that :)

**Pull request merged**
