### PR TITLE
feat(provider/AWS): Add functions support to Spinnaker UI.

### PR DESCRIPTION
**Pull request by saimadineni**
Issue: https://github.com/spinnaker/spinnaker/issues/4921Issue 
Summary:
Add functions support to Spinnaker UI. This is a net functionality that we've been working on for almost a year to this point. The initial backend work was done like three months back.
From then we've worked on creating the UI components with guidance from the Netflix UX team.

Cloud Provider(s): provider/AWS
Environment:
This worked on user's local environment and also through deploying docker images to kubernetes cluster.

Feature Area: @spinnaker/ui-ux-team
Description:
CRUD functionality for managing lambda functions, With this new we must be able to create, update and delete lambda lambda functions through Spinnaker UI
We must also be able to attach target groups to lambda functions using Spinnaker UI.
Additional Details:
Clouddriver backend details: https://github.com/spinnaker/clouddriver/tree/master/clouddriver-lambda

### CODE REVIEW

**Comment by alanmquach** [comment]
Is this ready for review?

There are items in here that don't seem intended to be merged, for example, `.favorites.json`, `package.json`, `yarn.lock` to name a few. Also the travis check has failed so I imagine that would require some changes.

Also it would help us get this reviewed it was split into a few smaller PRs.

**Comment by jeyrschabu** [comment]
Pinging @saimadineni. Is this ready for review?

**Comment by saimadineni** [comment]
Hey @jeyrschabu . Not yet. Still trying to fix the errors that has caused the Travis CI tests to fail.
Thanks.

**Comment by christopherthielen** [comment]
@saimadineni this code has been merged in separate PRs, so we can close this, right?

**Comment by saimadineni** [comment]
Yes. This can be closed.
I'm closing it now. Thanks

**Pull request closed without merging**
