### PR TITLE
fix(titus): Shimming the execution logs for preconfigured jobs

### PR DESCRIPTION
**Pull request by alanmquach**
I feel dirty just writing this code.

Quick fix band aid, but really we should have orca construct the URL and place it in the stage context.

Looking at that right now as well, so maybe we'll end up closing this PR.

### CODE REVIEW

**Comment by erikmunson** [comment]
Amazing

**Comment by anotherchrisberry** [comment]
@alanmquach do you want to merge this or do the thing in Orca?

**Comment by alanmquach** [comment]
If this doesn’t look too terrible, let’s merge this until the thing gets done in orca.

I took a quick look and it’s not as straightforward as I had hoped.

**Comment by anotherchrisberry** [comment]
It's pretty dirty. Let's make sure we do fix this in Orca!

**Comment by ethanfrogers** [comment]
@alanmquach I just noticed this fix. Hopefully I didn't cause any issues for you guys?

**Comment by alanmquach** [comment]
@ethanfrogers Nope! I don't think the logs had ever worked for titus. Just shimming this until we manage to construct the logs URL in orca so it can be cloud provider agnostic.

**Pull request merged**
