### PR TITLE
fix(kubernetes) remove upper limit for CPU Target on resize

### PR DESCRIPTION
**Pull request by kevinawoo**
same as https://github.com/spinnaker/deck/pull/5159, but for `release-1.6.x` branch.

### CODE REVIEW

**Comment by lwander** [comment]
If this is intended as a patch, it needs to go into `spinnaker:release-1.6.x`, right now it's still going into `spinnaker:master`.

**Comment by kevinawoo** [comment]
derp derp. I fixed it! Thanks for the 👀s

**Comment by lwander** [comment]
Sorry one more thing, can you tag this as a "fix" given that it's technically fixing a bug, and going into a patch release?

**Comment by lwander** [comment]
Thanks!

**Pull request merged**
