### PR TITLE
fix(core): bump up width on numerical form fields

### PR DESCRIPTION
**Pull request by gcomstock**
This addresses a Netflix customer concern that the width on the pipeline wait stage > wait time form field was too narrow. I took a look and saw the 60px style is used throughout deck, but I don't think it's necessary. I think a placeholder value or tooltips go further to instruct a user on the expected input vs the width of the form field. I wanted to get feedback from folks more familiar with the codebase than me though, so I'm just nudging up the width as a safe first step/conversation starter.

Here's a screen shot of the new width

Screen Shot 2020-03-31 at 12 49 44 PM

### CODE REVIEW

**Comment by erikmunson** [comment]
I dig it. I'm sure there are a few spots where we rely on this explicit width to lay things out, but it's probably not a big deal to mess with it or remove it altogether. A quick search says we only use that `inline-number` class in 14 files as of today anyways.

**Comment by erikmunson** [comment]
Actually yes, upon further inspection we do use it in some places where totally removing an explicit width would have an impact, e.g.:

Screen Shot 2020-03-31 at 1 52 46 PM

**Comment by erikmunson** [comment]
@gcomstock are you ready for me to merge this?

**Comment by gcomstock** [comment]
> @gcomstock are you ready for me to merge this?

Yes! Thank you!

**Pull request merged**
