### PR TITLE
refactor(core): move Ace Editor CSS to core module

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Might as well move it to core eh

### CODE REVIEW

**Comment by archana-s** [comment]
I wonder if it should be in a more specific CSS file and not forms.

**Comment by anotherchrisberry** [comment]
@archana-s fair question. My thinking was that the editor is a form, so it makes sense to put it here. But you could make an argument that it belongs in its own file.

**Comment by erikmunson** [comment]
+1 to giving it its own file. I don't really think this qualifies as a form in the sense we define it.

**Comment by anotherchrisberry** [comment]
Moved to its own file

**Pull request merged**
