### PR TITLE
do not open execution links in new window

### PR DESCRIPTION
**Pull request by anotherchrisberry**
The pipeline stage details has a link to the execution. Currently, it's set to open in a new window, which is really unhelpful for most folks, who are running child pipelines in the same application.

This set of changes will expand the section and attempt to scroll to that execution within the page.

Also adding a "details" link to the header, to make it more clear how to expand the details, per @tomaslin 's recommendation.

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@tomaslin please review eh

**Comment by tomaslin** [comment]
seems that the pipeline link in a strategy doesn't take into account expanded details and scrolls to an incorrect location.

**Comment by tomaslin** [comment]
an edge case here is : click on a link to a pipeline. Scroll down. Click link back to the pipeline we have navigated to -> doesn't scroll since url doesn't change

**Comment by anotherchrisberry** [comment]
Yeah, needs some work. I am working on it.

**Comment by anotherchrisberry** [comment]
@tomaslin okay, I updated it - should be handling that edge case now. Can you give it another shot?

**Comment by tomaslin** [comment]
child pipeline links in the stage ( View Pipeline Executions ) don't scroll correctly. I think because the parent pipeline details get collapsed

**Comment by tomaslin** [comment]
@anotherchrisberry is this ready to go?

**Comment by anotherchrisberry** [comment]
Yeah, it's as ready as it's going to be. Will look at providing a deep link into a single, filtered execution at some point, but that will be a separate PR.

**Pull request merged**
