### PR TITLE
fix(core): make chaos monkey opt-in for new apps

### PR DESCRIPTION
**Pull request by maggieneterval**
Closes https://github.com/spinnaker/spinnaker/issues/4095

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
Can we put this behind a feature flag (defaulting to `false`)? We still need it enabled by default at Netflix.

**Comment by jtk54** [comment]
It feels a little backwards to me to enable chaos on by default upstream. Is there a particular reason you can't flag it on?

**Comment by anotherchrisberry** [comment]
Sorry, that is what I am asking for: give us the ability to flag it on. We understand we're probably the exception at Netflix.

**Comment by jtk54** [comment]
> defaulting to `false`

Whoops I misread that, sorry.

**Comment by anotherchrisberry** [comment]
No worries, my wording was confusing!

**Comment by maggieneterval** [comment]
Just updated to add `newApplicationDefaults.chaosMonkey` to `spinnakerSettings`, defaulting to false. So now whether you've enabled the chaos monkey feature and whether you'd like it to be enabled by default in new applications are separate flags. Hopefully this works for everyone!

**Pull request merged**
