### PR TITLE
fix(core): ensure trigger type is set on the model

### PR DESCRIPTION
**Pull request by Jammy-Louie**

### CODE REVIEW

**Comment by Jammy-Louie** [comment]
Angular previously automatically handled this for and this was missed in the refactor

**Comment by maggieneterval** [comment]
Hey @Jammy-Louie, I think I already resolved the issue of setting the trigger type on the model with this PR: https://github.com/spinnaker/deck/pull/7241

However, as @christopherthielen mentioned in a comment on that PR, he found a separate issue that occurs when you add a second trigger after configuring the type of the first (I think?) -- are you looking into that? If not let me know and I can take a look. Thanks!

**Comment by christopherthielen** [comment]
I'm going to finish updating the netflix internal trigger, then I'll take a look at the trigger JSON merge issue

**Comment by Jammy-Louie** [comment]
@christopherthielen @maggieneterval 
I noticed that problem too. I was going to fix that and convert the last part `triggers.directive.js` to React

but first I need to fix some problem with manual executions

**Pull request closed without merging**
