### PR TITLE
feat(md): display manifest path and make it configurable

### PR DESCRIPTION
**Pull request by ranihorev**
This allows users to specify the location of the app's config file

image

image

### CODE REVIEW

**Comment by luispollo** [comment]
I recommend displaying the directory hosting the file, otherwise I think this will be confusing to users. We do that in the pipeline stage:

image

**Comment by ranihorev** [comment]
Yup, that's why I added the PR to keel. But I don't have that info in the
UI yet :)

**Comment by luispollo** [comment]
Yes you do. It's a setting in Deck:
https://github.com/spinnaker/deck/blob/b96078e304aad10f147bfeb65b91299c9033a6d1/packages/core/src/pipeline/config/stages/managed/ImportDeliveryConfigStageConfig.tsx#L22

**Comment by ranihorev** [comment]
Doh, I had no idea. I can probably revert my PR on keel then

**Comment by luispollo** [comment]
Yeah, sorry I missed that in the Keel PR. I also didn't think the reason for that was to consume in Deck when reviewing.

**Pull request merged**
