### PR TITLE
feat(core): allow parameters to be hidden based on other params

### PR DESCRIPTION
**Pull request by anotherchrisberry**
This might be a terrible idea, I don't know.

We've seen scenarios where folks have a lot of parameters in their pipelines, but some of those parameters are only applicable if other parameters are set, or if the trigger is a specific job. This would let them hide those parameters from the user starting the pipeline by adding a simple expression to the parameter's config.

Example: there are a lot of parameters for this pipeline that only make sense when the Regional Steps field has a non-zero value.
screen shot 2018-03-01 at 8 30 15 pm

By setting the `conditional` on those fields to `parameters.numberOfRegions !== '0'`, I can hide those fields and present a more intuitive experience for the user:
screen shot 2018-03-01 at 8 29 48 pm

To guard against completely arbitrary script execution, we push the evaluation into a web worker, and always return a boolean. 

I'm not exposing this field in the UI - I would like to experiment with it and try to poke holes in this before making it broadly available.

### CODE REVIEW

**Comment by tomaslin** [comment]
I don't like `conditional` because it is overloaded elsewhere ( conditionalOnExpression ). Any thoughts about renaming that something like `visibleWhen` or `visibleIf`? It's also not very clear that this is JavaScript and not SPEL.

**Comment by tomaslin** [comment]
In Pipeline stages, are we still showing all parameters? ( since those parameters can be SPEL )

**Comment by christopherthielen** [comment]
I don’t know how I feel about this.  I don’t love it but I don’t hate it either. I don’t love it because it’s more complexity and (I think?) will get limited use.

**Comment by erikmunson** [comment]
I don't love the idea of adding a bunch of worker + eval complexity for something that it seems will only solve a problem for a small subset of pipelines. I do, however, _really like_ the idea of avoiding all the confusion involved with the dependent field case for the pipelines that use this pattern.

Is there another way to design this that doesn't involve all this eval stuff? I can imagine maybe there's a way to do it via the UI with a somewhat restricted set of conditions to solve 90% of people's use cases?

**Comment by anotherchrisberry** [comment]
@erikmunson I thought about that. For my use case, these are the conditional expressions I've put together:
```
parseInt(parameters.numRegions) > 0
parseInt(parameters.numRegions) > 1
parseInt(parameters.numRegions) > 2
parseInt(parameters.numRegions) > 3
parameters.env === 'test'
```
If we supported parameter types, and could represent `numRegions` as a number instead of a string, we could probably get away with a simple grammar like
```
{
  "conditional": {
    "parameter": "numRegions",
    "comparator": ">" // or "=", "!=", ">=", etc.
    "comparatorValue": 0
  }
}
```
We could probably even do a `parseFloat` on the parameter if `>` or `<` were selected, and skip the parameter types. I think that would satisfy my use cases, and it would not be too hard to add UI elements to support entering it later.

Assuming we go with the restricted grammar above, what opinions do we have about the field names (parameter, comparator, comparatorValue)?

**Comment by erikmunson** [comment]
I like that WAY more. If the JSON looked like that and the UI inputs were nicely setup to let people configure them I'd say this is a 💯idea.

**Comment by anotherchrisberry** [comment]
superseded by https://github.com/spinnaker/deck/pull/4948

**Pull request closed without merging**
