### PR TITLE
(manualJudgment) Add full support for manualJudgmentContinue and manu…

### PR DESCRIPTION
**Pull request by duftler**
…alJudgmentStop notifications.
(manualJudgment) Bring notification configuration more in line with other stages.

### CODE REVIEW

**Comment by duftler** [comment]
Existing manual judgment stages will still be handled properly. Once a user edits an manual judgment stage in the pipeline editor, the configuration of any notifications will be updated to the newer style (this mostly means that instead of leaving it implicit that the notifications are for when the stage is awaiting judgment, the notifications are explicitly associated with 'manualJudgment').
The notification configuration ui matches that of the other stages.
The custom message for the awaiting judgment (i.e. manualJudgment) notification is still handled via the top-level 'Instructions' control.
Test that the notification configuration for Pipelines/Applications/Other stages still works as before these changes.

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
image

**Comment by duftler** [comment]
Depends on https://github.com/spinnaker/orca/pull/1089

**Comment by anotherchrisberry** [comment]
LGTM

**Pull request merged**
