### PR TITLE
feat(tencentcloud): add certificates, common, deploymentStrategy subnet folders and files for tencentcloud

### PR DESCRIPTION
**Pull request by zexiplus**
This PR aims to add certificates, common, deployment-strategy subnet folders and files for Tencent cloud. The cloud provider proposal is spinnaker/governance#79

### CODE REVIEW

**Comment by zexiplus** [comment]
> Hi @zexiplus, thanks for the PR!
> 
> The code itself looks fine, though it does seem like large parts of entire files were just copy/pasted from the Amazon provider. I don't know enough about Tencent cloud to understand whether this was a reasonable choice, but these types of PRs adding to the Tencent provider might be a bit easier to follow if I had a better idea of the functionality you were trying to achieve in each commit. For example, the `TencentcloudCertificateReader`, `ModalFooter`, etc. do not actually appear to be used anywhere (yet?). Perhaps it would make more sense to work backwards from registering different elements of the Tencent cloud provider in `tencentcloud.module.ts`: for example, you could make one PR that adds sever group components, one PR that adds load balancer components, etc.
> 
> Let me know what you think!

Thanks for your advice, 

> Hi @zexiplus, thanks for the PR!
> 
> The code itself looks fine, though it does seem like large parts of entire files were just copy/pasted from the Amazon provider. I don't know enough about Tencent cloud to understand whether this was a reasonable choice, but these types of PRs adding to the Tencent provider might be a bit easier to follow if I had a better idea of the functionality you were trying to achieve in each commit. For example, the `TencentcloudCertificateReader`, `ModalFooter`, etc. do not actually appear to be used anywhere (yet?). Perhaps it would make more sense to work backwards from registering different elements of the Tencent cloud provider in `tencentcloud.module.ts`: for example, you could make one PR that adds sever group components, one PR that adds load balancer components, etc.
> 
> Let me know what you think!



> Hi @zexiplus, thanks for the PR!
> 
> The code itself looks fine, though it does seem like large parts of entire files were just copy/pasted from the Amazon provider. I don't know enough about Tencent cloud to understand whether this was a reasonable choice, but these types of PRs adding to the Tencent provider might be a bit easier to follow if I had a better idea of the functionality you were trying to achieve in each commit. For example, the `TencentcloudCertificateReader`, `ModalFooter`, etc. do not actually appear to be used anywhere (yet?). Perhaps it would make more sense to work backwards from registering different elements of the Tencent cloud provider in `tencentcloud.module.ts`: for example, you could make one PR that adds sever group components, one PR that adds load balancer components, etc.
> 
> Let me know what you think!

Hello, @maggieneterval.  Thanks for your advice. 
Actually we have finished most of the work in another repository, but the repo's commit is not good to make PR. So we have to rearrange the code to a new repo, that's why it looks like copy/paste. We do learn from some other cloud provider cuz of we are not familiar with   
Spinnaker at the beginning and their code fragments are really in common use. But Tencent cloud provider does have its own feature, like bake, manual judgment, and so on(most of in the pipeline/stage module). That's all my thought, thanks for your reply.

**Comment by zexiplus** [comment]
> Hi @zexiplus, thanks for the PR!
> 
> The code itself looks fine, though it does seem like large parts of entire files were just copy/pasted from the Amazon provider. I don't know enough about Tencent cloud to understand whether this was a reasonable choice, but these types of PRs adding to the Tencent provider might be a bit easier to follow if I had a better idea of the functionality you were trying to achieve in each commit. For example, the `TencentcloudCertificateReader`, `ModalFooter`, etc. do not actually appear to be used anywhere (yet?). Perhaps it would make more sense to work backwards from registering different elements of the Tencent cloud provider in `tencentcloud.module.ts`: for example, you could make one PR that adds sever group components, one PR that adds load balancer components, etc.
> 
> Let me know what you think!

Hello, @maggieneterval. Thanks for your advice.
Actually we have finished most of the work in another repository, but the repo's commit is not good to make PR. So we have to rearrange the code to a new repo, that's why it looks like copy/paste. We do learn from some other cloud provider cuz of we are not familiar with
Spinnaker at the beginning and their code fragments are really in common use. But Tencent cloud provider does have its own feature, like bake, manual judgment, and so on(most of in the pipeline/stage module). That's all my thought, thanks for your reply.

**Comment by maggieneterval** [comment]
@zexiplus Thanks for your reply. I appreciate that you are in the process of upstreaming code from your own fork. That said, it's difficult to meaningfully review your PR as-is, since it's not even clear all of these files will be necessary. Could you please either reorganize this PR into commits that actually register components to `tencentcloud.module.ts`, or at least outline some plan to do so? I'm uncomfortable with merging this as-is. Thanks!

**Comment by zexiplus** [comment]
@maggieneterval Thanks for your advice again, I will refactor the code. This code will be closed now.

**Comment by zexiplus** [comment]
@maggieneterval Thanks for your advice again, I will refactor the code. This PR will be closed now

**Pull request closed without merging**
