### PR TITLE
feat(deck): Add execution error details to Task Status in Cloud foundry Stage (#7814)

### PR DESCRIPTION
**Pull request by spinnakerbot**
Co-authored-by: adevgsegarra <60253656+adevgsegarra@users.noreply.github.com>

> Automated cherry pick of e15b7964ac7c3025cf4567dbaf803fbf61d28d6b into 1.18

### CODE REVIEW

**Comment by duftler** [comment]
At first glance, this does look like a feature not a fix. If it's a feature, would have to wait for the next release instead of cherry-picking here.

**Comment by duftler** [comment]
@gerardsegarra @xavileon @ethanfrogers  Do you consider this a feature or a fix? Is it urgently needed in 1.18.x, or can it wait to be rolled out with 1.19?

**Comment by xavileon** [comment]
Yeah sorry, we can consider it a new feature. I cherry-picked it without realizing that policy given it was a small PR.
We can wait until 1.19.x :+1:

**Comment by duftler** [comment]
Sounds good. Thanks for the quick response, @xavileon .

**Pull request closed without merging**
