### PR TITLE
feat(Azure): Update UI to handle custom and managed images.

### PR DESCRIPTION
**Pull request by DanielaS12**
Managed image
image

Custom Image
image

### CODE REVIEW

**Review by sergio-quintero — APPROVED** [review]

**Comment by ovidiupopa07** [comment]
Can we add some tests for this functionality?

**Review by ovidiupopa07 — APPROVED** [review]

**Comment by DanielaS12** [comment]
> 

This part of deck is not tested at all and I do not see and improvement in adding it.

**Comment by DanielaS12** [comment]
needs to be merged after https://github.com/spinnaker/orca/pull/4335

**Review by nemesisOsorio — APPROVED** [review]

**Comment by DanielaS12** [comment]
@dbyron0 can you help me merge this?

**Comment by dogonthehorizon** [comment]
Approving now on the contingent that we make an effort to move towards React components in this provider.

**Review by dogonthehorizon — APPROVED** [review]

**Pull request merged**
