### PR TITLE
feat(pipeline): added feature flag for pipeline when mj stage child

### PR DESCRIPTION
**Pull request by OscarMichelH**
Base change from cherry-pick commit #9863 but feature flag logic was added.

Enable the UI characteristic with env variable:
`MJ_PARENTPIPELINE_ENABLED = true`

### CODE REVIEW

**Comment by OscarMichelH** [comment]
@dbyron-sf

**Comment by dbyron-sf** [comment]
Any chance @dogonthehorizon can take a look at this?

**Comment by ovidiupopa07** [comment]
hi @OscarMichelH . It seems that this feature introduces a bug.  See https://github.com/spinnaker/spinnaker/issues/6764 for more details.  How difficult do you think it would be to fix this?

**Review by ovidiupopa07 — CHANGES_REQUESTED** [review]
see my other comment

**Comment by OscarMichelH** [comment]
> hi @OscarMichelH . It seems that this feature introduces a bug (reproducible in 1.29).
> 
> `application.executions.data` -> if there are no executions available (`undefined` object) it will fail to read the `data` property See [spinnaker/spinnaker#6764](https://github.com/spinnaker/spinnaker/issues/6764) for more details. It would be nice to include this fix if it is not that difficult.

Added undefined verification for sub-pipes data 👍

**Comment by ovidiupopa07** [comment]
> > hi @OscarMichelH . It seems that this feature introduces a bug (reproducible in 1.29).
> > `application.executions.data` -> if there are no executions available (`undefined` object) it will fail to read the `data` property See [spinnaker/spinnaker#6764](https://github.com/spinnaker/spinnaker/issues/6764) for more details. It would be nice to include this fix if it is not that difficult.
> 
> Added undefined verification for sub-pipes data 👍

hi @OscarMichelH I think you should also add the `applications.executions != undefined ` check

**Comment by OscarMichelH** [comment]
> > > hi @OscarMichelH . It seems that this feature introduces a bug (reproducible in 1.29).
> > > `application.executions.data` -> if there are no executions available (`undefined` object) it will fail to read the `data` property See [spinnaker/spinnaker#6764](https://github.com/spinnaker/spinnaker/issues/6764) for more details. It would be nice to include this fix if it is not that difficult.
> > 
> > 
> > Added undefined verification for sub-pipes data 👍
> 
> hi @OscarMichelH I think you should also add the `applications.executions != undefined ` check. The error is about `executions` being undefined. If you verified that scenario and it is working everything is ok :)

Excellent, thank you @ovidiupopa07 , I added it the validation for application.executions, and keep the other application.executions just to cover the case where data can be undefined

**Review by dogonthehorizon — APPROVED** [review]

**Review by ovidiupopa07 — APPROVED** [review]

**Comment by dogonthehorizon** [comment]
@mergifyio backport release-1.27.x release-1.28.x release-1.29.x

**Pull request merged**
