### PR TITLE
feat(notification): add bearychat support.

### PR DESCRIPTION
**Pull request by abcsnowwolf**
Add a new notification type bearychat. 
This PR is related to [spinnaker/spinnaker#2874](https://github.com/spinnaker/spinnaker/issues/2874).

### CODE REVIEW

**Comment by abcsnowwolf** [comment]
Sorry. I have formated commit name.

**Comment by sbwsg** [comment]
These changes lgtm.  I suggest we wait until your PRs against orca, front50 and echo have been merged before merging this one.

**Comment by abcsnowwolf** [comment]
@sbwsg hi, Other three PRs have merged.

**Comment by sbwsg** [comment]
Thanks!

**Pull request merged**
