### PR TITLE
chore(core): update libs to latest

### PR DESCRIPTION
**Pull request by icfantv**
@jrsquared @christopherthielen @anotherchrisberry @danielpeach PTAL

### CODE REVIEW

**Comment by jrsquared** [comment]
Not sure what else is broken, but please test it first.

**Comment by icfantv** [comment]
@jrsquared yep, @christopherthielen just mentioned this as a bad side-effect.

**Comment by icfantv** [comment]
going to close this for now.

**Comment by jrsquared** [comment]
FWIW, this is _exactly_ why we have the yarn.lock file in the first place.

**Comment by icfantv** [comment]
@jrsquared yea, sorry for the noise.  Chris and I were screwing around trying to bring my dev environment back into the 21st century after some bitrot.

**Pull request closed without merging**
