### PR TITLE
fix(redblack): fixing redblack onchange values

### PR DESCRIPTION
**Pull request by shlomodaari**
This should fix this [issue](https://github.com/spinnaker/spinnaker/issues/6950) when values are not responding when using red/black strategy

### CODE REVIEW

**Comment by shlomodaari** [comment]
https://github.com/spinnaker/deck/assets/104773977/e921d321-0f2c-4ca9-86ea-b48315a065c0

**Comment by mattgogerly** [comment]
Thanks for the contribution! Mind cleaning up the linting errors so we can get this merged?

**Review by ovidiupopa07 — APPROVED** [review]
Thank you for the contribution. LGTM

**Comment by jasonmcintosh** [comment]
@mergifyio backport release-1.34.x release-1.33.x release-1.32.x

**Comment by jasonmcintosh** [comment]
@mergifyio backport release-1.28.x

**Pull request merged**
