### PR TITLE
chore: upgrade to react 16.8

### PR DESCRIPTION
**Pull request by maggieneterval**
- Upgrades `react` from 16.6.0 to ~16.8.0.
- Upgrades `react-dom` from 16.6.0 to ~16.8.0.
- Upgrades `@types/react` from ^16.4.18 to ~16.8.0
- Upgrades `@types/react-dom` from 16.0.5 to ~16.8.0.
- Resolves new Typescript error resulting from `@types/react` upgrade in `Overridable.tsx`: `Conversion of type 'ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<{}>>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.` I just did exactly what the error told me to do to fix this, but more creative solutions are welcome.
- Nothing _seems_ to have been broken by these upgrades, but I'll keep playing with it and am happy to sit on this for as long as we think is necessary to fully test everything!

### CODE REVIEW

**Comment by louisjimenez** [comment]
Nice! 👏 

`Would anyone prefer we upgrade to the most recent patch release instead?`

I think having a looser range to at least include patches could be helpful but perhaps there is some historical context /background to using pinned versions?

**Comment by maggieneterval** [comment]
> I think having a looser range to at least include patches could be helpful but perhaps there is some historical context /background to using pinned versions?

I had pinned it because it looks like that's what's been done in the past but I'll leave the call up to @christopherthielen :smile:

**Comment by christopherthielen** [comment]
> Upgrades react from 16.6.0 to 16.8.0. Would anyone prefer we upgrade to the most recent patch release instead?

Yes, I'd actually prefer semver range `~16.8.0` to indicate we target the latest patch release of `16.8`.  the `yarn.lock` file will keep us locked into a specific release until we explicitly  choose to upgrade to the next bugfix version

**Comment by anotherchrisberry** [comment]
Any reason not to upgrade the `@types/react*` to `16.8.*`? It looks like yarn is already resolving them to 16.8.x releases, and feels a little funny to have react on 16.8 but the typings a minor version below.

**Comment by anotherchrisberry** [comment]
Sorry @maggieneterval, I pushed the wrong button and did not mean to close this.

**Comment by maggieneterval** [comment]
Updated react, react-dom, types/react, and types/react-dom all to ~16.8.0. Re-ran tests and clicked around a bit and all seems to be well!

**Pull request merged**
